//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum PcnProgramError {
    /// 6000 - Only the configured admin may perform this action
    #[error("Only the configured admin may perform this action")]
    UnauthorizedAdmin = 0x1770,
    /// 6001 - Only the configured oracle may perform this action
    #[error("Only the configured oracle may perform this action")]
    UnauthorizedOracle = 0x1771,
    /// 6002 - Invalid curve parameters
    #[error("Invalid curve parameters")]
    InvalidCurveParams = 0x1772,
    /// 6003 - Invalid claim window
    #[error("Invalid claim window")]
    InvalidClaimWindow = 0x1773,
    /// 6004 - Invalid epoch slot window
    #[error("Invalid epoch slot window")]
    InvalidEpochWindow = 0x1774,
    /// 6005 - Invalid support budget
    #[error("Invalid support budget")]
    InvalidSupportBudget = 0x1775,
    /// 6006 - Epoch is not open
    #[error("Epoch is not open")]
    EpochNotOpen = 0x1776,
    /// 6007 - Epoch is not finalized
    #[error("Epoch is not finalized")]
    EpochNotFinalized = 0x1777,
    /// 6008 - Epoch claim deadline has passed
    #[error("Epoch claim deadline has passed")]
    ClaimDeadlinePassed = 0x1778,
    /// 6009 - Epoch claim deadline has not passed
    #[error("Epoch claim deadline has not passed")]
    ClaimWindowStillOpen = 0x1779,
    /// 6010 - Total reward weight must be greater than zero
    #[error("Total reward weight must be greater than zero")]
    ZeroTotalRewardWeight = 0x177A,
    /// 6011 - Quality factor exceeds 1.0x
    #[error("Quality factor exceeds 1.0x")]
    InvalidQualityFactor = 0x177B,
    /// 6012 - Reward pool is zero
    #[error("Reward pool is zero")]
    ZeroRewardPool = 0x177C,
    /// 6013 - Maximum curve supply is exhausted
    #[error("Maximum curve supply is exhausted")]
    MaxSupplyExhausted = 0x177D,
    /// 6014 - Claim allocation exceeds epoch reward pool
    #[error("Claim allocation exceeds epoch reward pool")]
    ClaimOverAllocation = 0x177E,
    /// 6015 - Claim already redeemed
    #[error("Claim already redeemed")]
    ClaimAlreadyRedeemed = 0x177F,
    /// 6016 - Claim account does not match epoch or user
    #[error("Claim account does not match epoch or user")]
    InvalidClaimAccount = 0x1780,
    /// 6017 - Reward mint or token account does not match config
    #[error("Reward mint or token account does not match config")]
    InvalidTokenAccount = 0x1781,
    /// 6018 - Arithmetic overflow or underflow
    #[error("Arithmetic overflow or underflow")]
    MathOverflow = 0x1782,
}

impl From<PcnProgramError> for solana_program_error::ProgramError {
    fn from(e: PcnProgramError) -> Self {
        solana_program_error::ProgramError::Custom(e as u32)
    }
}
