/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { PCN_PROGRAM_PROGRAM_ADDRESS } from "../programs";

/** UnauthorizedInitializer: Only the program upgrade authority may initialize the config */
export const PCN_PROGRAM_ERROR__UNAUTHORIZED_INITIALIZER = 0x1770; // 6000
/** InvalidProgramData: ProgramData does not belong to this program */
export const PCN_PROGRAM_ERROR__INVALID_PROGRAM_DATA = 0x1771; // 6001
/** UnauthorizedAdmin: Only the configured admin may perform this action */
export const PCN_PROGRAM_ERROR__UNAUTHORIZED_ADMIN = 0x1772; // 6002
/** UnauthorizedOracle: Only the configured oracle may perform this action */
export const PCN_PROGRAM_ERROR__UNAUTHORIZED_ORACLE = 0x1773; // 6003
/** InvalidCurveParams: Invalid curve parameters */
export const PCN_PROGRAM_ERROR__INVALID_CURVE_PARAMS = 0x1774; // 6004
/** InvalidClaimWindow: Invalid claim window */
export const PCN_PROGRAM_ERROR__INVALID_CLAIM_WINDOW = 0x1775; // 6005
/** InvalidEpochWindow: Invalid epoch slot window */
export const PCN_PROGRAM_ERROR__INVALID_EPOCH_WINDOW = 0x1776; // 6006
/** InvalidSupportBudget: Invalid support budget */
export const PCN_PROGRAM_ERROR__INVALID_SUPPORT_BUDGET = 0x1777; // 6007
/** EpochNotOpen: Epoch is not open */
export const PCN_PROGRAM_ERROR__EPOCH_NOT_OPEN = 0x1778; // 6008
/** EpochNotFinalized: Epoch is not finalized */
export const PCN_PROGRAM_ERROR__EPOCH_NOT_FINALIZED = 0x1779; // 6009
/** ClaimDeadlinePassed: Epoch claim deadline has passed */
export const PCN_PROGRAM_ERROR__CLAIM_DEADLINE_PASSED = 0x177a; // 6010
/** ClaimWindowStillOpen: Epoch claim deadline has not passed */
export const PCN_PROGRAM_ERROR__CLAIM_WINDOW_STILL_OPEN = 0x177b; // 6011
/** ZeroTotalRewardWeight: Total reward weight must be greater than zero */
export const PCN_PROGRAM_ERROR__ZERO_TOTAL_REWARD_WEIGHT = 0x177c; // 6012
/** InvalidPerformanceMetrics: Performance metrics must each be between zero and one million ppm */
export const PCN_PROGRAM_ERROR__INVALID_PERFORMANCE_METRICS = 0x177d; // 6013
/** InvalidPerformanceWeights: Performance weights must each be at most one million ppm and sum to one million ppm */
export const PCN_PROGRAM_ERROR__INVALID_PERFORMANCE_WEIGHTS = 0x177e; // 6014
/** ZeroRewardPool: Reward pool is zero */
export const PCN_PROGRAM_ERROR__ZERO_REWARD_POOL = 0x177f; // 6015
/** MaxSupplyExhausted: Maximum curve supply is exhausted */
export const PCN_PROGRAM_ERROR__MAX_SUPPLY_EXHAUSTED = 0x1780; // 6016
/** ClaimOverAllocation: Claim allocation exceeds epoch reward pool */
export const PCN_PROGRAM_ERROR__CLAIM_OVER_ALLOCATION = 0x1781; // 6017
/** ClaimAlreadyRedeemed: Claim already redeemed */
export const PCN_PROGRAM_ERROR__CLAIM_ALREADY_REDEEMED = 0x1782; // 6018
/** InvalidClaimAccount: Claim account does not match epoch or user */
export const PCN_PROGRAM_ERROR__INVALID_CLAIM_ACCOUNT = 0x1783; // 6019
/** InvalidTokenAccount: Reward mint or token account does not match config */
export const PCN_PROGRAM_ERROR__INVALID_TOKEN_ACCOUNT = 0x1784; // 6020
/** MathOverflow: Arithmetic overflow or underflow */
export const PCN_PROGRAM_ERROR__MATH_OVERFLOW = 0x1785; // 6021

export type PcnProgramError =
  | typeof PCN_PROGRAM_ERROR__CLAIM_ALREADY_REDEEMED
  | typeof PCN_PROGRAM_ERROR__CLAIM_DEADLINE_PASSED
  | typeof PCN_PROGRAM_ERROR__CLAIM_OVER_ALLOCATION
  | typeof PCN_PROGRAM_ERROR__CLAIM_WINDOW_STILL_OPEN
  | typeof PCN_PROGRAM_ERROR__EPOCH_NOT_FINALIZED
  | typeof PCN_PROGRAM_ERROR__EPOCH_NOT_OPEN
  | typeof PCN_PROGRAM_ERROR__INVALID_CLAIM_ACCOUNT
  | typeof PCN_PROGRAM_ERROR__INVALID_CLAIM_WINDOW
  | typeof PCN_PROGRAM_ERROR__INVALID_CURVE_PARAMS
  | typeof PCN_PROGRAM_ERROR__INVALID_EPOCH_WINDOW
  | typeof PCN_PROGRAM_ERROR__INVALID_PERFORMANCE_METRICS
  | typeof PCN_PROGRAM_ERROR__INVALID_PERFORMANCE_WEIGHTS
  | typeof PCN_PROGRAM_ERROR__INVALID_PROGRAM_DATA
  | typeof PCN_PROGRAM_ERROR__INVALID_SUPPORT_BUDGET
  | typeof PCN_PROGRAM_ERROR__INVALID_TOKEN_ACCOUNT
  | typeof PCN_PROGRAM_ERROR__MATH_OVERFLOW
  | typeof PCN_PROGRAM_ERROR__MAX_SUPPLY_EXHAUSTED
  | typeof PCN_PROGRAM_ERROR__UNAUTHORIZED_ADMIN
  | typeof PCN_PROGRAM_ERROR__UNAUTHORIZED_INITIALIZER
  | typeof PCN_PROGRAM_ERROR__UNAUTHORIZED_ORACLE
  | typeof PCN_PROGRAM_ERROR__ZERO_REWARD_POOL
  | typeof PCN_PROGRAM_ERROR__ZERO_TOTAL_REWARD_WEIGHT;

let pcnProgramErrorMessages: Record<PcnProgramError, string> | undefined;
if (process.env["NODE_ENV"] !== "production") {
  pcnProgramErrorMessages = {
    [PCN_PROGRAM_ERROR__CLAIM_ALREADY_REDEEMED]: `Claim already redeemed`,
    [PCN_PROGRAM_ERROR__CLAIM_DEADLINE_PASSED]: `Epoch claim deadline has passed`,
    [PCN_PROGRAM_ERROR__CLAIM_OVER_ALLOCATION]: `Claim allocation exceeds epoch reward pool`,
    [PCN_PROGRAM_ERROR__CLAIM_WINDOW_STILL_OPEN]: `Epoch claim deadline has not passed`,
    [PCN_PROGRAM_ERROR__EPOCH_NOT_FINALIZED]: `Epoch is not finalized`,
    [PCN_PROGRAM_ERROR__EPOCH_NOT_OPEN]: `Epoch is not open`,
    [PCN_PROGRAM_ERROR__INVALID_CLAIM_ACCOUNT]: `Claim account does not match epoch or user`,
    [PCN_PROGRAM_ERROR__INVALID_CLAIM_WINDOW]: `Invalid claim window`,
    [PCN_PROGRAM_ERROR__INVALID_CURVE_PARAMS]: `Invalid curve parameters`,
    [PCN_PROGRAM_ERROR__INVALID_EPOCH_WINDOW]: `Invalid epoch slot window`,
    [PCN_PROGRAM_ERROR__INVALID_PERFORMANCE_METRICS]: `Performance metrics must each be between zero and one million ppm`,
    [PCN_PROGRAM_ERROR__INVALID_PERFORMANCE_WEIGHTS]: `Performance weights must each be at most one million ppm and sum to one million ppm`,
    [PCN_PROGRAM_ERROR__INVALID_PROGRAM_DATA]: `ProgramData does not belong to this program`,
    [PCN_PROGRAM_ERROR__INVALID_SUPPORT_BUDGET]: `Invalid support budget`,
    [PCN_PROGRAM_ERROR__INVALID_TOKEN_ACCOUNT]: `Reward mint or token account does not match config`,
    [PCN_PROGRAM_ERROR__MATH_OVERFLOW]: `Arithmetic overflow or underflow`,
    [PCN_PROGRAM_ERROR__MAX_SUPPLY_EXHAUSTED]: `Maximum curve supply is exhausted`,
    [PCN_PROGRAM_ERROR__UNAUTHORIZED_ADMIN]: `Only the configured admin may perform this action`,
    [PCN_PROGRAM_ERROR__UNAUTHORIZED_INITIALIZER]: `Only the program upgrade authority may initialize the config`,
    [PCN_PROGRAM_ERROR__UNAUTHORIZED_ORACLE]: `Only the configured oracle may perform this action`,
    [PCN_PROGRAM_ERROR__ZERO_REWARD_POOL]: `Reward pool is zero`,
    [PCN_PROGRAM_ERROR__ZERO_TOTAL_REWARD_WEIGHT]: `Total reward weight must be greater than zero`,
  };
}

export function getPcnProgramErrorMessage(code: PcnProgramError): string {
  if (process.env["NODE_ENV"] !== "production") {
    return (pcnProgramErrorMessages as Record<PcnProgramError, string>)[code];
  }

  return "Error message not available in production bundles.";
}

export function isPcnProgramError<TProgramErrorCode extends PcnProgramError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    PCN_PROGRAM_PROGRAM_ADDRESS,
    code
  );
}
