/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type CurveParams = {
  maxEpochMint: bigint;
  emissionMultiplierPpm: bigint;
  saturationUnits: bigint;
  historyMinted: bigint;
  targetSupportLamportsPerToken: bigint;
  maxSupply: bigint;
};

export type CurveParamsArgs = {
  maxEpochMint: number | bigint;
  emissionMultiplierPpm: number | bigint;
  saturationUnits: number | bigint;
  historyMinted: number | bigint;
  targetSupportLamportsPerToken: number | bigint;
  maxSupply: number | bigint;
};

export function getCurveParamsEncoder(): FixedSizeEncoder<CurveParamsArgs> {
  return getStructEncoder([
    ["maxEpochMint", getU64Encoder()],
    ["emissionMultiplierPpm", getU64Encoder()],
    ["saturationUnits", getU64Encoder()],
    ["historyMinted", getU64Encoder()],
    ["targetSupportLamportsPerToken", getU64Encoder()],
    ["maxSupply", getU64Encoder()],
  ]);
}

export function getCurveParamsDecoder(): FixedSizeDecoder<CurveParams> {
  return getStructDecoder([
    ["maxEpochMint", getU64Decoder()],
    ["emissionMultiplierPpm", getU64Decoder()],
    ["saturationUnits", getU64Decoder()],
    ["historyMinted", getU64Decoder()],
    ["targetSupportLamportsPerToken", getU64Decoder()],
    ["maxSupply", getU64Decoder()],
  ]);
}

export function getCurveParamsCodec(): FixedSizeCodec<
  CurveParamsArgs,
  CurveParams
> {
  return combineCodec(getCurveParamsEncoder(), getCurveParamsDecoder());
}
