/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export enum EpochStatus {
  Open,
  Finalized,
  Swept,
}

export type EpochStatusArgs = EpochStatus;

export function getEpochStatusEncoder(): FixedSizeEncoder<EpochStatusArgs> {
  return getEnumEncoder(EpochStatus);
}

export function getEpochStatusDecoder(): FixedSizeDecoder<EpochStatus> {
  return getEnumDecoder(EpochStatus);
}

export function getEpochStatusCodec(): FixedSizeCodec<
  EpochStatusArgs,
  EpochStatus
> {
  return combineCodec(getEpochStatusEncoder(), getEpochStatusDecoder());
}
