/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type PerformanceMetrics = {
  uptimePpm: bigint;
  bandwidthPpm: bigint;
  fulfilmentRatePpm: bigint;
  questScorePpm: bigint;
};

export type PerformanceMetricsArgs = {
  uptimePpm: number | bigint;
  bandwidthPpm: number | bigint;
  fulfilmentRatePpm: number | bigint;
  questScorePpm: number | bigint;
};

export function getPerformanceMetricsEncoder(): FixedSizeEncoder<PerformanceMetricsArgs> {
  return getStructEncoder([
    ["uptimePpm", getU64Encoder()],
    ["bandwidthPpm", getU64Encoder()],
    ["fulfilmentRatePpm", getU64Encoder()],
    ["questScorePpm", getU64Encoder()],
  ]);
}

export function getPerformanceMetricsDecoder(): FixedSizeDecoder<PerformanceMetrics> {
  return getStructDecoder([
    ["uptimePpm", getU64Decoder()],
    ["bandwidthPpm", getU64Decoder()],
    ["fulfilmentRatePpm", getU64Decoder()],
    ["questScorePpm", getU64Decoder()],
  ]);
}

export function getPerformanceMetricsCodec(): FixedSizeCodec<
  PerformanceMetricsArgs,
  PerformanceMetrics
> {
  return combineCodec(
    getPerformanceMetricsEncoder(),
    getPerformanceMetricsDecoder()
  );
}
