/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type PerformanceWeights = {
  uptimePpm: bigint;
  bandwidthPpm: bigint;
  fulfilmentRatePpm: bigint;
  questScorePpm: bigint;
};

export type PerformanceWeightsArgs = {
  uptimePpm: number | bigint;
  bandwidthPpm: number | bigint;
  fulfilmentRatePpm: number | bigint;
  questScorePpm: number | bigint;
};

export function getPerformanceWeightsEncoder(): FixedSizeEncoder<PerformanceWeightsArgs> {
  return getStructEncoder([
    ["uptimePpm", getU64Encoder()],
    ["bandwidthPpm", getU64Encoder()],
    ["fulfilmentRatePpm", getU64Encoder()],
    ["questScorePpm", getU64Encoder()],
  ]);
}

export function getPerformanceWeightsDecoder(): FixedSizeDecoder<PerformanceWeights> {
  return getStructDecoder([
    ["uptimePpm", getU64Decoder()],
    ["bandwidthPpm", getU64Decoder()],
    ["fulfilmentRatePpm", getU64Decoder()],
    ["questScorePpm", getU64Decoder()],
  ]);
}

export function getPerformanceWeightsCodec(): FixedSizeCodec<
  PerformanceWeightsArgs,
  PerformanceWeights
> {
  return combineCodec(
    getPerformanceWeightsEncoder(),
    getPerformanceWeightsDecoder()
  );
}
