/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  getBytesEncoder,
  getProgramDerivedAddress,
  type Address,
  type ProgramDerivedAddress,
} from "@solana/kit";

export async function findSolReservePda(
  config: { programAddress?: Address | undefined } = {}
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "86oGodFG8DfLYHAgYwUPCNQzaods7Auxz9cnU7XzWipt" as Address<"86oGodFG8DfLYHAgYwUPCNQzaods7Auxz9cnU7XzWipt">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getBytesEncoder().encode(
        new Uint8Array([115, 111, 108, 95, 114, 101, 115, 101, 114, 118, 101])
      ),
    ],
  });
}
