//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_address::{address, Address};

/// `pcn_program` program ID.
pub const PCN_PROGRAM_ID: Address = address!("86oGodFG8DfLYHAgYwUPCNQzaods7Auxz9cnU7XzWipt");
