//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::codama_rust::types::PerformanceMetrics;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_address::Address;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct Claim {
    pub discriminator: [u8; 8],
    pub epoch: Address,
    pub epoch_id: u64,
    pub user: Address,
    pub performance: PerformanceMetrics,
    pub reward_weight: u64,
    pub reward_amount: u64,
    pub claimed: bool,
    pub bump: u8,
}

pub const CLAIM_DISCRIMINATOR: [u8; 8] = [155, 70, 22, 176, 123, 215, 246, 102];

impl Claim {
    pub const LEN: usize = 130;

    #[inline(always)]
    pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
        let mut data = data;
        Self::deserialize(&mut data)
    }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for Claim {
    type Error = std::io::Error;

    fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
        let mut data: &[u8] = &(*account_info.data).borrow();
        Self::deserialize(&mut data)
    }
}

#[cfg(feature = "fetch")]
pub fn fetch_claim(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    address: &solana_address::Address,
) -> Result<crate::shared::DecodedAccount<Claim>, std::io::Error> {
    let accounts = fetch_all_claim(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_claim(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    addresses: &[solana_address::Address],
) -> Result<Vec<crate::shared::DecodedAccount<Claim>>, std::io::Error> {
    let accounts = rpc
        .get_multiple_accounts(addresses)
        .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::DecodedAccount<Claim>> = Vec::new();
    for i in 0..addresses.len() {
        let address = addresses[i];
        let account = accounts[i].as_ref().ok_or(std::io::Error::other(format!(
            "Account not found: {address}"
        )))?;
        let data = Claim::from_bytes(&account.data)?;
        decoded_accounts.push(crate::shared::DecodedAccount {
            address,
            account: account.clone(),
            data,
        });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_claim(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    address: &solana_address::Address,
) -> Result<crate::shared::MaybeAccount<Claim>, std::io::Error> {
    let accounts = fetch_all_maybe_claim(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_claim(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    addresses: &[solana_address::Address],
) -> Result<Vec<crate::shared::MaybeAccount<Claim>>, std::io::Error> {
    let accounts = rpc
        .get_multiple_accounts(addresses)
        .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::MaybeAccount<Claim>> = Vec::new();
    for i in 0..addresses.len() {
        let address = addresses[i];
        if let Some(account) = accounts[i].as_ref() {
            let data = Claim::from_bytes(&account.data)?;
            decoded_accounts.push(crate::shared::MaybeAccount::Exists(
                crate::shared::DecodedAccount {
                    address,
                    account: account.clone(),
                    data,
                },
            ));
        } else {
            decoded_accounts.push(crate::shared::MaybeAccount::NotFound(address));
        }
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "anchor")]
impl anchor_lang::AccountDeserialize for Claim {
    fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
    }
}

#[cfg(feature = "anchor")]
impl anchor_lang::AccountSerialize for Claim {}

#[cfg(feature = "anchor")]
impl anchor_lang::Owner for Claim {
    fn owner() -> anchor_lang::solana_program::pubkey::Pubkey {
        anchor_lang::solana_program::pubkey::Pubkey::from(crate::PCN_PROGRAM_ID.to_bytes())
    }
}

#[cfg(feature = "anchor-idl-build")]
impl anchor_lang::IdlBuild for Claim {}

#[cfg(feature = "anchor-idl-build")]
impl anchor_lang::Discriminator for Claim {
    const DISCRIMINATOR: &[u8] = &[0; 8];
}
