//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#claim;
pub(crate) mod r#config;
pub(crate) mod r#epoch;
pub(crate) mod r#sol_reserve;

pub use self::r#claim::*;
pub use self::r#config::*;
pub use self::r#epoch::*;
pub use self::r#sol_reserve::*;
