//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct PerformanceMetrics {
    pub uptime_ppm: u64,
    pub bandwidth_ppm: u64,
    pub fulfilment_rate_ppm: u64,
    pub quest_score_ppm: u64,
}
