/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const CLAIM_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  155, 70, 22, 176, 123, 215, 246, 102,
]);

export function getClaimDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CLAIM_DISCRIMINATOR);
}

export type Claim = {
  discriminator: ReadonlyUint8Array;
  epoch: Address;
  epochId: bigint;
  user: Address;
  bandwidthUnits: bigint;
  qualityFactorPpm: bigint;
  rewardWeight: bigint;
  rewardAmount: bigint;
  claimed: boolean;
  bump: number;
};

export type ClaimArgs = {
  epoch: Address;
  epochId: number | bigint;
  user: Address;
  bandwidthUnits: number | bigint;
  qualityFactorPpm: number | bigint;
  rewardWeight: number | bigint;
  rewardAmount: number | bigint;
  claimed: boolean;
  bump: number;
};

/** Gets the encoder for {@link ClaimArgs} account data. */
export function getClaimEncoder(): FixedSizeEncoder<ClaimArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["epoch", getAddressEncoder()],
      ["epochId", getU64Encoder()],
      ["user", getAddressEncoder()],
      ["bandwidthUnits", getU64Encoder()],
      ["qualityFactorPpm", getU64Encoder()],
      ["rewardWeight", getU64Encoder()],
      ["rewardAmount", getU64Encoder()],
      ["claimed", getBooleanEncoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CLAIM_DISCRIMINATOR })
  );
}

/** Gets the decoder for {@link Claim} account data. */
export function getClaimDecoder(): FixedSizeDecoder<Claim> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["epoch", getAddressDecoder()],
    ["epochId", getU64Decoder()],
    ["user", getAddressDecoder()],
    ["bandwidthUnits", getU64Decoder()],
    ["qualityFactorPpm", getU64Decoder()],
    ["rewardWeight", getU64Decoder()],
    ["rewardAmount", getU64Decoder()],
    ["claimed", getBooleanDecoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link Claim} account data. */
export function getClaimCodec(): FixedSizeCodec<ClaimArgs, Claim> {
  return combineCodec(getClaimEncoder(), getClaimDecoder());
}

export function decodeClaim<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<Claim, TAddress>;
export function decodeClaim<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<Claim, TAddress>;
export function decodeClaim<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<Claim, TAddress> | MaybeAccount<Claim, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getClaimDecoder()
  );
}

export async function fetchClaim<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<Claim, TAddress>> {
  const maybeAccount = await fetchMaybeClaim(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeClaim<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<Claim, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeClaim(maybeAccount);
}

export async function fetchAllClaim(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<Claim>[]> {
  const maybeAccounts = await fetchAllMaybeClaim(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeClaim(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<Claim>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeClaim(maybeAccount));
}

export function getClaimSize(): number {
  return 114;
}
