/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getCurveParamsDecoder,
  getCurveParamsEncoder,
  type CurveParams,
  type CurveParamsArgs,
} from "../types";

export const CONFIG_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  155, 12, 170, 224, 30, 250, 204, 130,
]);

export function getConfigDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CONFIG_DISCRIMINATOR);
}

export type Config = {
  discriminator: ReadonlyUint8Array;
  admin: Address;
  oracle: Address;
  rewardMint: Address;
  mintAuthorityBump: number;
  configBump: number;
  solReserve: Address;
  solReserveBump: number;
  tokenReserveVault: Address;
  tokenReserveBump: number;
  lifetimeCurveMintedAmount: bigint;
  claimWindowSlots: bigint;
  curve: CurveParams;
};

export type ConfigArgs = {
  admin: Address;
  oracle: Address;
  rewardMint: Address;
  mintAuthorityBump: number;
  configBump: number;
  solReserve: Address;
  solReserveBump: number;
  tokenReserveVault: Address;
  tokenReserveBump: number;
  lifetimeCurveMintedAmount: number | bigint;
  claimWindowSlots: number | bigint;
  curve: CurveParamsArgs;
};

/** Gets the encoder for {@link ConfigArgs} account data. */
export function getConfigEncoder(): FixedSizeEncoder<ConfigArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["admin", getAddressEncoder()],
      ["oracle", getAddressEncoder()],
      ["rewardMint", getAddressEncoder()],
      ["mintAuthorityBump", getU8Encoder()],
      ["configBump", getU8Encoder()],
      ["solReserve", getAddressEncoder()],
      ["solReserveBump", getU8Encoder()],
      ["tokenReserveVault", getAddressEncoder()],
      ["tokenReserveBump", getU8Encoder()],
      ["lifetimeCurveMintedAmount", getU64Encoder()],
      ["claimWindowSlots", getU64Encoder()],
      ["curve", getCurveParamsEncoder()],
    ]),
    (value) => ({ ...value, discriminator: CONFIG_DISCRIMINATOR })
  );
}

/** Gets the decoder for {@link Config} account data. */
export function getConfigDecoder(): FixedSizeDecoder<Config> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["admin", getAddressDecoder()],
    ["oracle", getAddressDecoder()],
    ["rewardMint", getAddressDecoder()],
    ["mintAuthorityBump", getU8Decoder()],
    ["configBump", getU8Decoder()],
    ["solReserve", getAddressDecoder()],
    ["solReserveBump", getU8Decoder()],
    ["tokenReserveVault", getAddressDecoder()],
    ["tokenReserveBump", getU8Decoder()],
    ["lifetimeCurveMintedAmount", getU64Decoder()],
    ["claimWindowSlots", getU64Decoder()],
    ["curve", getCurveParamsDecoder()],
  ]);
}

/** Gets the codec for {@link Config} account data. */
export function getConfigCodec(): FixedSizeCodec<ConfigArgs, Config> {
  return combineCodec(getConfigEncoder(), getConfigDecoder());
}

export function decodeConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<Config, TAddress>;
export function decodeConfig<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<Config, TAddress>;
export function decodeConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<Config, TAddress> | MaybeAccount<Config, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getConfigDecoder()
  );
}

export async function fetchConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<Config, TAddress>> {
  const maybeAccount = await fetchMaybeConfig(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<Config, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeConfig(maybeAccount);
}

export async function fetchAllConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<Config>[]> {
  const maybeAccounts = await fetchAllMaybeConfig(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<Config>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeConfig(maybeAccount));
}

export function getConfigSize(): number {
  return 228;
}
