/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getEpochStatusDecoder,
  getEpochStatusEncoder,
  getPerformanceWeightsDecoder,
  getPerformanceWeightsEncoder,
  type EpochStatus,
  type EpochStatusArgs,
  type PerformanceWeights,
  type PerformanceWeightsArgs,
} from "../types";

export const EPOCH_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  93, 83, 120, 89, 151, 138, 152, 108,
]);

export function getEpochDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(EPOCH_DISCRIMINATOR);
}

export type Epoch = {
  discriminator: ReadonlyUint8Array;
  epochId: bigint;
  status: EpochStatus;
  startSlot: bigint;
  endSlot: bigint;
  supportBudgetLamports: bigint;
  consumedSupportLamports: bigint;
  totalRewardWeight: bigint;
  rewardPoolAmount: bigint;
  allocatedAmount: bigint;
  claimedAmount: bigint;
  claimDeadlineSlot: bigint;
  epochTokenVault: Address;
  epochVaultBump: number;
  bump: number;
  performanceWeights: PerformanceWeights;
};

export type EpochArgs = {
  epochId: number | bigint;
  status: EpochStatusArgs;
  startSlot: number | bigint;
  endSlot: number | bigint;
  supportBudgetLamports: number | bigint;
  consumedSupportLamports: number | bigint;
  totalRewardWeight: number | bigint;
  rewardPoolAmount: number | bigint;
  allocatedAmount: number | bigint;
  claimedAmount: number | bigint;
  claimDeadlineSlot: number | bigint;
  epochTokenVault: Address;
  epochVaultBump: number;
  bump: number;
  performanceWeights: PerformanceWeightsArgs;
};

/** Gets the encoder for {@link EpochArgs} account data. */
export function getEpochEncoder(): FixedSizeEncoder<EpochArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["epochId", getU64Encoder()],
      ["status", getEpochStatusEncoder()],
      ["startSlot", getU64Encoder()],
      ["endSlot", getU64Encoder()],
      ["supportBudgetLamports", getU64Encoder()],
      ["consumedSupportLamports", getU64Encoder()],
      ["totalRewardWeight", getU64Encoder()],
      ["rewardPoolAmount", getU64Encoder()],
      ["allocatedAmount", getU64Encoder()],
      ["claimedAmount", getU64Encoder()],
      ["claimDeadlineSlot", getU64Encoder()],
      ["epochTokenVault", getAddressEncoder()],
      ["epochVaultBump", getU8Encoder()],
      ["bump", getU8Encoder()],
      ["performanceWeights", getPerformanceWeightsEncoder()],
    ]),
    (value) => ({ ...value, discriminator: EPOCH_DISCRIMINATOR })
  );
}

/** Gets the decoder for {@link Epoch} account data. */
export function getEpochDecoder(): FixedSizeDecoder<Epoch> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["epochId", getU64Decoder()],
    ["status", getEpochStatusDecoder()],
    ["startSlot", getU64Decoder()],
    ["endSlot", getU64Decoder()],
    ["supportBudgetLamports", getU64Decoder()],
    ["consumedSupportLamports", getU64Decoder()],
    ["totalRewardWeight", getU64Decoder()],
    ["rewardPoolAmount", getU64Decoder()],
    ["allocatedAmount", getU64Decoder()],
    ["claimedAmount", getU64Decoder()],
    ["claimDeadlineSlot", getU64Decoder()],
    ["epochTokenVault", getAddressDecoder()],
    ["epochVaultBump", getU8Decoder()],
    ["bump", getU8Decoder()],
    ["performanceWeights", getPerformanceWeightsDecoder()],
  ]);
}

/** Gets the codec for {@link Epoch} account data. */
export function getEpochCodec(): FixedSizeCodec<EpochArgs, Epoch> {
  return combineCodec(getEpochEncoder(), getEpochDecoder());
}

export function decodeEpoch<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<Epoch, TAddress>;
export function decodeEpoch<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<Epoch, TAddress>;
export function decodeEpoch<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<Epoch, TAddress> | MaybeAccount<Epoch, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getEpochDecoder()
  );
}

export async function fetchEpoch<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<Epoch, TAddress>> {
  const maybeAccount = await fetchMaybeEpoch(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeEpoch<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<Epoch, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeEpoch(maybeAccount);
}

export async function fetchAllEpoch(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<Epoch>[]> {
  const maybeAccounts = await fetchAllMaybeEpoch(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeEpoch(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<Epoch>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeEpoch(maybeAccount));
}

export function getEpochSize(): number {
  return 155;
}
