/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const SOL_RESERVE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  78, 170, 214, 85, 103, 74, 70, 180,
]);

export function getSolReserveDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(SOL_RESERVE_DISCRIMINATOR);
}

export type SolReserve = { discriminator: ReadonlyUint8Array };

export type SolReserveArgs = {};

/** Gets the encoder for {@link SolReserveArgs} account data. */
export function getSolReserveEncoder(): FixedSizeEncoder<SolReserveArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: SOL_RESERVE_DISCRIMINATOR })
  );
}

/** Gets the decoder for {@link SolReserve} account data. */
export function getSolReserveDecoder(): FixedSizeDecoder<SolReserve> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

/** Gets the codec for {@link SolReserve} account data. */
export function getSolReserveCodec(): FixedSizeCodec<
  SolReserveArgs,
  SolReserve
> {
  return combineCodec(getSolReserveEncoder(), getSolReserveDecoder());
}

export function decodeSolReserve<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<SolReserve, TAddress>;
export function decodeSolReserve<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<SolReserve, TAddress>;
export function decodeSolReserve<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<SolReserve, TAddress> | MaybeAccount<SolReserve, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getSolReserveDecoder()
  );
}

export async function fetchSolReserve<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<SolReserve, TAddress>> {
  const maybeAccount = await fetchMaybeSolReserve(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeSolReserve<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<SolReserve, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeSolReserve(maybeAccount);
}

export async function fetchAllSolReserve(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<SolReserve>[]> {
  const maybeAccounts = await fetchAllMaybeSolReserve(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeSolReserve(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<SolReserve>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeSolReserve(maybeAccount));
}

export function getSolReserveSize(): number {
  return 8;
}
