/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findConfigPda, findMintAuthorityPda } from "../pdas";
import { PCN_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const CLAIM_REWARD_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  149, 95, 181, 242, 94, 90, 158, 162,
]);

export function getClaimRewardDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLAIM_REWARD_DISCRIMINATOR
  );
}

export type ClaimRewardInstruction<
  TProgram extends string = typeof PCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountEpoch extends string | AccountMeta<string> = string,
  TAccountClaim extends string | AccountMeta<string> = string,
  TAccountEpochTokenVault extends string | AccountMeta<string> = string,
  TAccountUserTokenAccount extends string | AccountMeta<string> = string,
  TAccountMintAuthority extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? ReadonlySignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountEpoch extends string
        ? WritableAccount<TAccountEpoch>
        : TAccountEpoch,
      TAccountClaim extends string
        ? WritableAccount<TAccountClaim>
        : TAccountClaim,
      TAccountEpochTokenVault extends string
        ? WritableAccount<TAccountEpochTokenVault>
        : TAccountEpochTokenVault,
      TAccountUserTokenAccount extends string
        ? WritableAccount<TAccountUserTokenAccount>
        : TAccountUserTokenAccount,
      TAccountMintAuthority extends string
        ? ReadonlyAccount<TAccountMintAuthority>
        : TAccountMintAuthority,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts
    ]
  >;

export type ClaimRewardInstructionData = {
  discriminator: ReadonlyUint8Array;
  epochId: bigint;
};

export type ClaimRewardInstructionDataArgs = { epochId: number | bigint };

export function getClaimRewardInstructionDataEncoder(): FixedSizeEncoder<ClaimRewardInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["epochId", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CLAIM_REWARD_DISCRIMINATOR })
  );
}

export function getClaimRewardInstructionDataDecoder(): FixedSizeDecoder<ClaimRewardInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["epochId", getU64Decoder()],
  ]);
}

export function getClaimRewardInstructionDataCodec(): FixedSizeCodec<
  ClaimRewardInstructionDataArgs,
  ClaimRewardInstructionData
> {
  return combineCodec(
    getClaimRewardInstructionDataEncoder(),
    getClaimRewardInstructionDataDecoder()
  );
}

export type ClaimRewardAsyncInput<
  TAccountUser extends string = string,
  TAccountConfig extends string = string,
  TAccountEpoch extends string = string,
  TAccountClaim extends string = string,
  TAccountEpochTokenVault extends string = string,
  TAccountUserTokenAccount extends string = string,
  TAccountMintAuthority extends string = string,
  TAccountTokenProgram extends string = string
> = {
  user: TransactionSigner<TAccountUser>;
  config?: Address<TAccountConfig>;
  epoch: Address<TAccountEpoch>;
  claim: Address<TAccountClaim>;
  epochTokenVault: Address<TAccountEpochTokenVault>;
  userTokenAccount: Address<TAccountUserTokenAccount>;
  mintAuthority?: Address<TAccountMintAuthority>;
  tokenProgram?: Address<TAccountTokenProgram>;
  epochId: ClaimRewardInstructionDataArgs["epochId"];
};

export async function getClaimRewardInstructionAsync<
  TAccountUser extends string,
  TAccountConfig extends string,
  TAccountEpoch extends string,
  TAccountClaim extends string,
  TAccountEpochTokenVault extends string,
  TAccountUserTokenAccount extends string,
  TAccountMintAuthority extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof PCN_PROGRAM_PROGRAM_ADDRESS
>(
  input: ClaimRewardAsyncInput<
    TAccountUser,
    TAccountConfig,
    TAccountEpoch,
    TAccountClaim,
    TAccountEpochTokenVault,
    TAccountUserTokenAccount,
    TAccountMintAuthority,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  ClaimRewardInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountConfig,
    TAccountEpoch,
    TAccountClaim,
    TAccountEpochTokenVault,
    TAccountUserTokenAccount,
    TAccountMintAuthority,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    epoch: { value: input.epoch ?? null, isWritable: true },
    claim: { value: input.claim ?? null, isWritable: true },
    epochTokenVault: { value: input.epochTokenVault ?? null, isWritable: true },
    userTokenAccount: {
      value: input.userTokenAccount ?? null,
      isWritable: true,
    },
    mintAuthority: { value: input.mintAuthority ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.mintAuthority.value) {
    accounts.mintAuthority.value = await findMintAuthorityPda();
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("user", accounts.user),
      getAccountMeta("config", accounts.config),
      getAccountMeta("epoch", accounts.epoch),
      getAccountMeta("claim", accounts.claim),
      getAccountMeta("epochTokenVault", accounts.epochTokenVault),
      getAccountMeta("userTokenAccount", accounts.userTokenAccount),
      getAccountMeta("mintAuthority", accounts.mintAuthority),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getClaimRewardInstructionDataEncoder().encode(
      args as ClaimRewardInstructionDataArgs
    ),
    programAddress,
  } as ClaimRewardInstruction<TProgramAddress, TAccountUser, TAccountConfig, TAccountEpoch, TAccountClaim, TAccountEpochTokenVault, TAccountUserTokenAccount, TAccountMintAuthority, TAccountTokenProgram>);
}

export type ClaimRewardInput<
  TAccountUser extends string = string,
  TAccountConfig extends string = string,
  TAccountEpoch extends string = string,
  TAccountClaim extends string = string,
  TAccountEpochTokenVault extends string = string,
  TAccountUserTokenAccount extends string = string,
  TAccountMintAuthority extends string = string,
  TAccountTokenProgram extends string = string
> = {
  user: TransactionSigner<TAccountUser>;
  config: Address<TAccountConfig>;
  epoch: Address<TAccountEpoch>;
  claim: Address<TAccountClaim>;
  epochTokenVault: Address<TAccountEpochTokenVault>;
  userTokenAccount: Address<TAccountUserTokenAccount>;
  mintAuthority: Address<TAccountMintAuthority>;
  tokenProgram?: Address<TAccountTokenProgram>;
  epochId: ClaimRewardInstructionDataArgs["epochId"];
};

export function getClaimRewardInstruction<
  TAccountUser extends string,
  TAccountConfig extends string,
  TAccountEpoch extends string,
  TAccountClaim extends string,
  TAccountEpochTokenVault extends string,
  TAccountUserTokenAccount extends string,
  TAccountMintAuthority extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof PCN_PROGRAM_PROGRAM_ADDRESS
>(
  input: ClaimRewardInput<
    TAccountUser,
    TAccountConfig,
    TAccountEpoch,
    TAccountClaim,
    TAccountEpochTokenVault,
    TAccountUserTokenAccount,
    TAccountMintAuthority,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): ClaimRewardInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountConfig,
  TAccountEpoch,
  TAccountClaim,
  TAccountEpochTokenVault,
  TAccountUserTokenAccount,
  TAccountMintAuthority,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? PCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    epoch: { value: input.epoch ?? null, isWritable: true },
    claim: { value: input.claim ?? null, isWritable: true },
    epochTokenVault: { value: input.epochTokenVault ?? null, isWritable: true },
    userTokenAccount: {
      value: input.userTokenAccount ?? null,
      isWritable: true,
    },
    mintAuthority: { value: input.mintAuthority ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("user", accounts.user),
      getAccountMeta("config", accounts.config),
      getAccountMeta("epoch", accounts.epoch),
      getAccountMeta("claim", accounts.claim),
      getAccountMeta("epochTokenVault", accounts.epochTokenVault),
      getAccountMeta("userTokenAccount", accounts.userTokenAccount),
      getAccountMeta("mintAuthority", accounts.mintAuthority),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getClaimRewardInstructionDataEncoder().encode(
      args as ClaimRewardInstructionDataArgs
    ),
    programAddress,
  } as ClaimRewardInstruction<TProgramAddress, TAccountUser, TAccountConfig, TAccountEpoch, TAccountClaim, TAccountEpochTokenVault, TAccountUserTokenAccount, TAccountMintAuthority, TAccountTokenProgram>);
}

export type ParsedClaimRewardInstruction<
  TProgram extends string = typeof PCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    config: TAccountMetas[1];
    epoch: TAccountMetas[2];
    claim: TAccountMetas[3];
    epochTokenVault: TAccountMetas[4];
    userTokenAccount: TAccountMetas[5];
    mintAuthority: TAccountMetas[6];
    tokenProgram: TAccountMetas[7];
  };
  data: ClaimRewardInstructionData;
};

export function parseClaimRewardInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[]
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedClaimRewardInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 8,
      }
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      config: getNextAccount(),
      epoch: getNextAccount(),
      claim: getNextAccount(),
      epochTokenVault: getNextAccount(),
      userTokenAccount: getNextAccount(),
      mintAuthority: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getClaimRewardInstructionDataDecoder().decode(instruction.data),
  };
}
