/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findConfigPda } from "../pdas";
import { PCN_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const CREATE_CLAIM_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  71, 122, 43, 84, 240, 165, 215, 181,
]);

export function getCreateClaimDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_CLAIM_DISCRIMINATOR
  );
}

export type CreateClaimInstruction<
  TProgram extends string = typeof PCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountOracle extends string | AccountMeta<string> = string,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountEpoch extends string | AccountMeta<string> = string,
  TAccountClaim extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOracle extends string
        ? ReadonlySignerAccount<TAccountOracle> &
            AccountSignerMeta<TAccountOracle>
        : TAccountOracle,
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountEpoch extends string
        ? WritableAccount<TAccountEpoch>
        : TAccountEpoch,
      TAccountClaim extends string
        ? WritableAccount<TAccountClaim>
        : TAccountClaim,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts
    ]
  >;

export type CreateClaimInstructionData = {
  discriminator: ReadonlyUint8Array;
  epochId: bigint;
  user: Address;
  bandwidthUnits: bigint;
  qualityFactorPpm: bigint;
};

export type CreateClaimInstructionDataArgs = {
  epochId: number | bigint;
  user: Address;
  bandwidthUnits: number | bigint;
  qualityFactorPpm: number | bigint;
};

export function getCreateClaimInstructionDataEncoder(): FixedSizeEncoder<CreateClaimInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["epochId", getU64Encoder()],
      ["user", getAddressEncoder()],
      ["bandwidthUnits", getU64Encoder()],
      ["qualityFactorPpm", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CREATE_CLAIM_DISCRIMINATOR })
  );
}

export function getCreateClaimInstructionDataDecoder(): FixedSizeDecoder<CreateClaimInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["epochId", getU64Decoder()],
    ["user", getAddressDecoder()],
    ["bandwidthUnits", getU64Decoder()],
    ["qualityFactorPpm", getU64Decoder()],
  ]);
}

export function getCreateClaimInstructionDataCodec(): FixedSizeCodec<
  CreateClaimInstructionDataArgs,
  CreateClaimInstructionData
> {
  return combineCodec(
    getCreateClaimInstructionDataEncoder(),
    getCreateClaimInstructionDataDecoder()
  );
}

export type CreateClaimAsyncInput<
  TAccountOracle extends string = string,
  TAccountPayer extends string = string,
  TAccountConfig extends string = string,
  TAccountEpoch extends string = string,
  TAccountClaim extends string = string,
  TAccountSystemProgram extends string = string
> = {
  oracle: TransactionSigner<TAccountOracle>;
  payer: TransactionSigner<TAccountPayer>;
  config?: Address<TAccountConfig>;
  epoch: Address<TAccountEpoch>;
  claim: Address<TAccountClaim>;
  systemProgram?: Address<TAccountSystemProgram>;
  epochId: CreateClaimInstructionDataArgs["epochId"];
  user: CreateClaimInstructionDataArgs["user"];
  bandwidthUnits: CreateClaimInstructionDataArgs["bandwidthUnits"];
  qualityFactorPpm: CreateClaimInstructionDataArgs["qualityFactorPpm"];
};

export async function getCreateClaimInstructionAsync<
  TAccountOracle extends string,
  TAccountPayer extends string,
  TAccountConfig extends string,
  TAccountEpoch extends string,
  TAccountClaim extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof PCN_PROGRAM_PROGRAM_ADDRESS
>(
  input: CreateClaimAsyncInput<
    TAccountOracle,
    TAccountPayer,
    TAccountConfig,
    TAccountEpoch,
    TAccountClaim,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  CreateClaimInstruction<
    TProgramAddress,
    TAccountOracle,
    TAccountPayer,
    TAccountConfig,
    TAccountEpoch,
    TAccountClaim,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    oracle: { value: input.oracle ?? null, isWritable: false },
    payer: { value: input.payer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    epoch: { value: input.epoch ?? null, isWritable: true },
    claim: { value: input.claim ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("oracle", accounts.oracle),
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("epoch", accounts.epoch),
      getAccountMeta("claim", accounts.claim),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getCreateClaimInstructionDataEncoder().encode(
      args as CreateClaimInstructionDataArgs
    ),
    programAddress,
  } as CreateClaimInstruction<TProgramAddress, TAccountOracle, TAccountPayer, TAccountConfig, TAccountEpoch, TAccountClaim, TAccountSystemProgram>);
}

export type CreateClaimInput<
  TAccountOracle extends string = string,
  TAccountPayer extends string = string,
  TAccountConfig extends string = string,
  TAccountEpoch extends string = string,
  TAccountClaim extends string = string,
  TAccountSystemProgram extends string = string
> = {
  oracle: TransactionSigner<TAccountOracle>;
  payer: TransactionSigner<TAccountPayer>;
  config: Address<TAccountConfig>;
  epoch: Address<TAccountEpoch>;
  claim: Address<TAccountClaim>;
  systemProgram?: Address<TAccountSystemProgram>;
  epochId: CreateClaimInstructionDataArgs["epochId"];
  user: CreateClaimInstructionDataArgs["user"];
  bandwidthUnits: CreateClaimInstructionDataArgs["bandwidthUnits"];
  qualityFactorPpm: CreateClaimInstructionDataArgs["qualityFactorPpm"];
};

export function getCreateClaimInstruction<
  TAccountOracle extends string,
  TAccountPayer extends string,
  TAccountConfig extends string,
  TAccountEpoch extends string,
  TAccountClaim extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof PCN_PROGRAM_PROGRAM_ADDRESS
>(
  input: CreateClaimInput<
    TAccountOracle,
    TAccountPayer,
    TAccountConfig,
    TAccountEpoch,
    TAccountClaim,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): CreateClaimInstruction<
  TProgramAddress,
  TAccountOracle,
  TAccountPayer,
  TAccountConfig,
  TAccountEpoch,
  TAccountClaim,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? PCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    oracle: { value: input.oracle ?? null, isWritable: false },
    payer: { value: input.payer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    epoch: { value: input.epoch ?? null, isWritable: true },
    claim: { value: input.claim ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("oracle", accounts.oracle),
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("epoch", accounts.epoch),
      getAccountMeta("claim", accounts.claim),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getCreateClaimInstructionDataEncoder().encode(
      args as CreateClaimInstructionDataArgs
    ),
    programAddress,
  } as CreateClaimInstruction<TProgramAddress, TAccountOracle, TAccountPayer, TAccountConfig, TAccountEpoch, TAccountClaim, TAccountSystemProgram>);
}

export type ParsedCreateClaimInstruction<
  TProgram extends string = typeof PCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
  programAddress: Address<TProgram>;
  accounts: {
    oracle: TAccountMetas[0];
    payer: TAccountMetas[1];
    config: TAccountMetas[2];
    epoch: TAccountMetas[3];
    claim: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
  };
  data: CreateClaimInstructionData;
};

export function parseCreateClaimInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[]
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCreateClaimInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 6,
      }
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      oracle: getNextAccount(),
      payer: getNextAccount(),
      config: getNextAccount(),
      epoch: getNextAccount(),
      claim: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateClaimInstructionDataDecoder().decode(instruction.data),
  };
}
