/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import {
  findConfigPda,
  findMintAuthorityPda,
  findSolReservePda,
} from "../pdas";
import { PCN_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const FINALIZE_EPOCH_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  159, 93, 117, 217, 63, 44, 249, 76,
]);

export function getFinalizeEpochDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    FINALIZE_EPOCH_DISCRIMINATOR
  );
}

export type FinalizeEpochInstruction<
  TProgram extends string = typeof PCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountOracle extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountEpoch extends string | AccountMeta<string> = string,
  TAccountSupportFunder extends string | AccountMeta<string> = string,
  TAccountEpochTokenVault extends string | AccountMeta<string> = string,
  TAccountRewardMint extends string | AccountMeta<string> = string,
  TAccountMintAuthority extends string | AccountMeta<string> = string,
  TAccountSolReserve extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOracle extends string
        ? ReadonlySignerAccount<TAccountOracle> &
            AccountSignerMeta<TAccountOracle>
        : TAccountOracle,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountEpoch extends string
        ? WritableAccount<TAccountEpoch>
        : TAccountEpoch,
      TAccountSupportFunder extends string
        ? WritableAccount<TAccountSupportFunder>
        : TAccountSupportFunder,
      TAccountEpochTokenVault extends string
        ? WritableAccount<TAccountEpochTokenVault>
        : TAccountEpochTokenVault,
      TAccountRewardMint extends string
        ? WritableAccount<TAccountRewardMint>
        : TAccountRewardMint,
      TAccountMintAuthority extends string
        ? ReadonlyAccount<TAccountMintAuthority>
        : TAccountMintAuthority,
      TAccountSolReserve extends string
        ? WritableAccount<TAccountSolReserve>
        : TAccountSolReserve,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts
    ]
  >;

export type FinalizeEpochInstructionData = {
  discriminator: ReadonlyUint8Array;
  totalRewardWeight: bigint;
};

export type FinalizeEpochInstructionDataArgs = {
  totalRewardWeight: number | bigint;
};

export function getFinalizeEpochInstructionDataEncoder(): FixedSizeEncoder<FinalizeEpochInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["totalRewardWeight", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: FINALIZE_EPOCH_DISCRIMINATOR })
  );
}

export function getFinalizeEpochInstructionDataDecoder(): FixedSizeDecoder<FinalizeEpochInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["totalRewardWeight", getU64Decoder()],
  ]);
}

export function getFinalizeEpochInstructionDataCodec(): FixedSizeCodec<
  FinalizeEpochInstructionDataArgs,
  FinalizeEpochInstructionData
> {
  return combineCodec(
    getFinalizeEpochInstructionDataEncoder(),
    getFinalizeEpochInstructionDataDecoder()
  );
}

export type FinalizeEpochAsyncInput<
  TAccountOracle extends string = string,
  TAccountConfig extends string = string,
  TAccountEpoch extends string = string,
  TAccountSupportFunder extends string = string,
  TAccountEpochTokenVault extends string = string,
  TAccountRewardMint extends string = string,
  TAccountMintAuthority extends string = string,
  TAccountSolReserve extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string
> = {
  oracle: TransactionSigner<TAccountOracle>;
  config?: Address<TAccountConfig>;
  epoch: Address<TAccountEpoch>;
  supportFunder: Address<TAccountSupportFunder>;
  epochTokenVault: Address<TAccountEpochTokenVault>;
  rewardMint: Address<TAccountRewardMint>;
  mintAuthority?: Address<TAccountMintAuthority>;
  solReserve?: Address<TAccountSolReserve>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  totalRewardWeight: FinalizeEpochInstructionDataArgs["totalRewardWeight"];
};

export async function getFinalizeEpochInstructionAsync<
  TAccountOracle extends string,
  TAccountConfig extends string,
  TAccountEpoch extends string,
  TAccountSupportFunder extends string,
  TAccountEpochTokenVault extends string,
  TAccountRewardMint extends string,
  TAccountMintAuthority extends string,
  TAccountSolReserve extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof PCN_PROGRAM_PROGRAM_ADDRESS
>(
  input: FinalizeEpochAsyncInput<
    TAccountOracle,
    TAccountConfig,
    TAccountEpoch,
    TAccountSupportFunder,
    TAccountEpochTokenVault,
    TAccountRewardMint,
    TAccountMintAuthority,
    TAccountSolReserve,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  FinalizeEpochInstruction<
    TProgramAddress,
    TAccountOracle,
    TAccountConfig,
    TAccountEpoch,
    TAccountSupportFunder,
    TAccountEpochTokenVault,
    TAccountRewardMint,
    TAccountMintAuthority,
    TAccountSolReserve,
    TAccountTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    oracle: { value: input.oracle ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: true },
    epoch: { value: input.epoch ?? null, isWritable: true },
    supportFunder: { value: input.supportFunder ?? null, isWritable: true },
    epochTokenVault: { value: input.epochTokenVault ?? null, isWritable: true },
    rewardMint: { value: input.rewardMint ?? null, isWritable: true },
    mintAuthority: { value: input.mintAuthority ?? null, isWritable: false },
    solReserve: { value: input.solReserve ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.mintAuthority.value) {
    accounts.mintAuthority.value = await findMintAuthorityPda();
  }
  if (!accounts.solReserve.value) {
    accounts.solReserve.value = await findSolReservePda();
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("oracle", accounts.oracle),
      getAccountMeta("config", accounts.config),
      getAccountMeta("epoch", accounts.epoch),
      getAccountMeta("supportFunder", accounts.supportFunder),
      getAccountMeta("epochTokenVault", accounts.epochTokenVault),
      getAccountMeta("rewardMint", accounts.rewardMint),
      getAccountMeta("mintAuthority", accounts.mintAuthority),
      getAccountMeta("solReserve", accounts.solReserve),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getFinalizeEpochInstructionDataEncoder().encode(
      args as FinalizeEpochInstructionDataArgs
    ),
    programAddress,
  } as FinalizeEpochInstruction<TProgramAddress, TAccountOracle, TAccountConfig, TAccountEpoch, TAccountSupportFunder, TAccountEpochTokenVault, TAccountRewardMint, TAccountMintAuthority, TAccountSolReserve, TAccountTokenProgram, TAccountSystemProgram>);
}

export type FinalizeEpochInput<
  TAccountOracle extends string = string,
  TAccountConfig extends string = string,
  TAccountEpoch extends string = string,
  TAccountSupportFunder extends string = string,
  TAccountEpochTokenVault extends string = string,
  TAccountRewardMint extends string = string,
  TAccountMintAuthority extends string = string,
  TAccountSolReserve extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string
> = {
  oracle: TransactionSigner<TAccountOracle>;
  config: Address<TAccountConfig>;
  epoch: Address<TAccountEpoch>;
  supportFunder: Address<TAccountSupportFunder>;
  epochTokenVault: Address<TAccountEpochTokenVault>;
  rewardMint: Address<TAccountRewardMint>;
  mintAuthority: Address<TAccountMintAuthority>;
  solReserve: Address<TAccountSolReserve>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  totalRewardWeight: FinalizeEpochInstructionDataArgs["totalRewardWeight"];
};

export function getFinalizeEpochInstruction<
  TAccountOracle extends string,
  TAccountConfig extends string,
  TAccountEpoch extends string,
  TAccountSupportFunder extends string,
  TAccountEpochTokenVault extends string,
  TAccountRewardMint extends string,
  TAccountMintAuthority extends string,
  TAccountSolReserve extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof PCN_PROGRAM_PROGRAM_ADDRESS
>(
  input: FinalizeEpochInput<
    TAccountOracle,
    TAccountConfig,
    TAccountEpoch,
    TAccountSupportFunder,
    TAccountEpochTokenVault,
    TAccountRewardMint,
    TAccountMintAuthority,
    TAccountSolReserve,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): FinalizeEpochInstruction<
  TProgramAddress,
  TAccountOracle,
  TAccountConfig,
  TAccountEpoch,
  TAccountSupportFunder,
  TAccountEpochTokenVault,
  TAccountRewardMint,
  TAccountMintAuthority,
  TAccountSolReserve,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? PCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    oracle: { value: input.oracle ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: true },
    epoch: { value: input.epoch ?? null, isWritable: true },
    supportFunder: { value: input.supportFunder ?? null, isWritable: true },
    epochTokenVault: { value: input.epochTokenVault ?? null, isWritable: true },
    rewardMint: { value: input.rewardMint ?? null, isWritable: true },
    mintAuthority: { value: input.mintAuthority ?? null, isWritable: false },
    solReserve: { value: input.solReserve ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("oracle", accounts.oracle),
      getAccountMeta("config", accounts.config),
      getAccountMeta("epoch", accounts.epoch),
      getAccountMeta("supportFunder", accounts.supportFunder),
      getAccountMeta("epochTokenVault", accounts.epochTokenVault),
      getAccountMeta("rewardMint", accounts.rewardMint),
      getAccountMeta("mintAuthority", accounts.mintAuthority),
      getAccountMeta("solReserve", accounts.solReserve),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getFinalizeEpochInstructionDataEncoder().encode(
      args as FinalizeEpochInstructionDataArgs
    ),
    programAddress,
  } as FinalizeEpochInstruction<TProgramAddress, TAccountOracle, TAccountConfig, TAccountEpoch, TAccountSupportFunder, TAccountEpochTokenVault, TAccountRewardMint, TAccountMintAuthority, TAccountSolReserve, TAccountTokenProgram, TAccountSystemProgram>);
}

export type ParsedFinalizeEpochInstruction<
  TProgram extends string = typeof PCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
  programAddress: Address<TProgram>;
  accounts: {
    oracle: TAccountMetas[0];
    config: TAccountMetas[1];
    epoch: TAccountMetas[2];
    supportFunder: TAccountMetas[3];
    epochTokenVault: TAccountMetas[4];
    rewardMint: TAccountMetas[5];
    mintAuthority: TAccountMetas[6];
    solReserve: TAccountMetas[7];
    tokenProgram: TAccountMetas[8];
    systemProgram: TAccountMetas[9];
  };
  data: FinalizeEpochInstructionData;
};

export function parseFinalizeEpochInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[]
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedFinalizeEpochInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 10) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 10,
      }
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      oracle: getNextAccount(),
      config: getNextAccount(),
      epoch: getNextAccount(),
      supportFunder: getNextAccount(),
      epochTokenVault: getNextAccount(),
      rewardMint: getNextAccount(),
      mintAuthority: getNextAccount(),
      solReserve: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getFinalizeEpochInstructionDataDecoder().decode(instruction.data),
  };
}
