/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import {
  findConfigPda,
  findMintAuthorityPda,
  findSolReservePda,
  findTokenReserveVaultPda,
} from "../pdas";
import { PCN_PROGRAM_PROGRAM_ADDRESS } from "../programs";
import {
  getCurveParamsDecoder,
  getCurveParamsEncoder,
  type CurveParams,
  type CurveParamsArgs,
} from "../types";

export const INITIALIZE_CONFIG_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([208, 127, 21, 1, 194, 190, 196, 70]);

export function getInitializeConfigDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_CONFIG_DISCRIMINATOR
  );
}

export type InitializeConfigInstruction<
  TProgram extends string = typeof PCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountRewardMint extends string | AccountMeta<string> = string,
  TAccountMintAuthority extends string | AccountMeta<string> = string,
  TAccountSolReserve extends string | AccountMeta<string> = string,
  TAccountTokenReserveVault extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = "11111111111111111111111111111111",
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountRent extends
    | string
    | AccountMeta<string> = "SysvarRent111111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountRewardMint extends string
        ? WritableSignerAccount<TAccountRewardMint> &
            AccountSignerMeta<TAccountRewardMint>
        : TAccountRewardMint,
      TAccountMintAuthority extends string
        ? ReadonlyAccount<TAccountMintAuthority>
        : TAccountMintAuthority,
      TAccountSolReserve extends string
        ? WritableAccount<TAccountSolReserve>
        : TAccountSolReserve,
      TAccountTokenReserveVault extends string
        ? WritableAccount<TAccountTokenReserveVault>
        : TAccountTokenReserveVault,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      ...TRemainingAccounts
    ]
  >;

export type InitializeConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  admin: Address;
  oracle: Address;
  claimWindowSlots: bigint;
  curve: CurveParams;
};

export type InitializeConfigInstructionDataArgs = {
  admin: Address;
  oracle: Address;
  claimWindowSlots: number | bigint;
  curve: CurveParamsArgs;
};

export function getInitializeConfigInstructionDataEncoder(): FixedSizeEncoder<InitializeConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["admin", getAddressEncoder()],
      ["oracle", getAddressEncoder()],
      ["claimWindowSlots", getU64Encoder()],
      ["curve", getCurveParamsEncoder()],
    ]),
    (value) => ({ ...value, discriminator: INITIALIZE_CONFIG_DISCRIMINATOR })
  );
}

export function getInitializeConfigInstructionDataDecoder(): FixedSizeDecoder<InitializeConfigInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["admin", getAddressDecoder()],
    ["oracle", getAddressDecoder()],
    ["claimWindowSlots", getU64Decoder()],
    ["curve", getCurveParamsDecoder()],
  ]);
}

export function getInitializeConfigInstructionDataCodec(): FixedSizeCodec<
  InitializeConfigInstructionDataArgs,
  InitializeConfigInstructionData
> {
  return combineCodec(
    getInitializeConfigInstructionDataEncoder(),
    getInitializeConfigInstructionDataDecoder()
  );
}

export type InitializeConfigAsyncInput<
  TAccountPayer extends string = string,
  TAccountConfig extends string = string,
  TAccountRewardMint extends string = string,
  TAccountMintAuthority extends string = string,
  TAccountSolReserve extends string = string,
  TAccountTokenReserveVault extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string
> = {
  payer: TransactionSigner<TAccountPayer>;
  config?: Address<TAccountConfig>;
  rewardMint: TransactionSigner<TAccountRewardMint>;
  mintAuthority?: Address<TAccountMintAuthority>;
  solReserve?: Address<TAccountSolReserve>;
  tokenReserveVault?: Address<TAccountTokenReserveVault>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  rent?: Address<TAccountRent>;
  admin: InitializeConfigInstructionDataArgs["admin"];
  oracle: InitializeConfigInstructionDataArgs["oracle"];
  claimWindowSlots: InitializeConfigInstructionDataArgs["claimWindowSlots"];
  curve: InitializeConfigInstructionDataArgs["curve"];
};

export async function getInitializeConfigInstructionAsync<
  TAccountPayer extends string,
  TAccountConfig extends string,
  TAccountRewardMint extends string,
  TAccountMintAuthority extends string,
  TAccountSolReserve extends string,
  TAccountTokenReserveVault extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof PCN_PROGRAM_PROGRAM_ADDRESS
>(
  input: InitializeConfigAsyncInput<
    TAccountPayer,
    TAccountConfig,
    TAccountRewardMint,
    TAccountMintAuthority,
    TAccountSolReserve,
    TAccountTokenReserveVault,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  InitializeConfigInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountConfig,
    TAccountRewardMint,
    TAccountMintAuthority,
    TAccountSolReserve,
    TAccountTokenReserveVault,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: true },
    rewardMint: { value: input.rewardMint ?? null, isWritable: true },
    mintAuthority: { value: input.mintAuthority ?? null, isWritable: false },
    solReserve: { value: input.solReserve ?? null, isWritable: true },
    tokenReserveVault: {
      value: input.tokenReserveVault ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.mintAuthority.value) {
    accounts.mintAuthority.value = await findMintAuthorityPda();
  }
  if (!accounts.solReserve.value) {
    accounts.solReserve.value = await findSolReservePda();
  }
  if (!accounts.tokenReserveVault.value) {
    accounts.tokenReserveVault.value = await findTokenReserveVaultPda();
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("rewardMint", accounts.rewardMint),
      getAccountMeta("mintAuthority", accounts.mintAuthority),
      getAccountMeta("solReserve", accounts.solReserve),
      getAccountMeta("tokenReserveVault", accounts.tokenReserveVault),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("rent", accounts.rent),
    ],
    data: getInitializeConfigInstructionDataEncoder().encode(
      args as InitializeConfigInstructionDataArgs
    ),
    programAddress,
  } as InitializeConfigInstruction<TProgramAddress, TAccountPayer, TAccountConfig, TAccountRewardMint, TAccountMintAuthority, TAccountSolReserve, TAccountTokenReserveVault, TAccountSystemProgram, TAccountTokenProgram, TAccountRent>);
}

export type InitializeConfigInput<
  TAccountPayer extends string = string,
  TAccountConfig extends string = string,
  TAccountRewardMint extends string = string,
  TAccountMintAuthority extends string = string,
  TAccountSolReserve extends string = string,
  TAccountTokenReserveVault extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountRent extends string = string
> = {
  payer: TransactionSigner<TAccountPayer>;
  config: Address<TAccountConfig>;
  rewardMint: TransactionSigner<TAccountRewardMint>;
  mintAuthority: Address<TAccountMintAuthority>;
  solReserve: Address<TAccountSolReserve>;
  tokenReserveVault: Address<TAccountTokenReserveVault>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  rent?: Address<TAccountRent>;
  admin: InitializeConfigInstructionDataArgs["admin"];
  oracle: InitializeConfigInstructionDataArgs["oracle"];
  claimWindowSlots: InitializeConfigInstructionDataArgs["claimWindowSlots"];
  curve: InitializeConfigInstructionDataArgs["curve"];
};

export function getInitializeConfigInstruction<
  TAccountPayer extends string,
  TAccountConfig extends string,
  TAccountRewardMint extends string,
  TAccountMintAuthority extends string,
  TAccountSolReserve extends string,
  TAccountTokenReserveVault extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof PCN_PROGRAM_PROGRAM_ADDRESS
>(
  input: InitializeConfigInput<
    TAccountPayer,
    TAccountConfig,
    TAccountRewardMint,
    TAccountMintAuthority,
    TAccountSolReserve,
    TAccountTokenReserveVault,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress }
): InitializeConfigInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountConfig,
  TAccountRewardMint,
  TAccountMintAuthority,
  TAccountSolReserve,
  TAccountTokenReserveVault,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountRent
> {
  // Program address.
  const programAddress = config?.programAddress ?? PCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: true },
    rewardMint: { value: input.rewardMint ?? null, isWritable: true },
    mintAuthority: { value: input.mintAuthority ?? null, isWritable: false },
    solReserve: { value: input.solReserve ?? null, isWritable: true },
    tokenReserveVault: {
      value: input.tokenReserveVault ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("rewardMint", accounts.rewardMint),
      getAccountMeta("mintAuthority", accounts.mintAuthority),
      getAccountMeta("solReserve", accounts.solReserve),
      getAccountMeta("tokenReserveVault", accounts.tokenReserveVault),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("rent", accounts.rent),
    ],
    data: getInitializeConfigInstructionDataEncoder().encode(
      args as InitializeConfigInstructionDataArgs
    ),
    programAddress,
  } as InitializeConfigInstruction<TProgramAddress, TAccountPayer, TAccountConfig, TAccountRewardMint, TAccountMintAuthority, TAccountSolReserve, TAccountTokenReserveVault, TAccountSystemProgram, TAccountTokenProgram, TAccountRent>);
}

export type ParsedInitializeConfigInstruction<
  TProgram extends string = typeof PCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    config: TAccountMetas[1];
    rewardMint: TAccountMetas[2];
    mintAuthority: TAccountMetas[3];
    solReserve: TAccountMetas[4];
    tokenReserveVault: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
    tokenProgram: TAccountMetas[7];
    rent: TAccountMetas[8];
  };
  data: InitializeConfigInstructionData;
};

export function parseInitializeConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[]
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedInitializeConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 9,
      }
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      config: getNextAccount(),
      rewardMint: getNextAccount(),
      mintAuthority: getNextAccount(),
      solReserve: getNextAccount(),
      tokenReserveVault: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      rent: getNextAccount(),
    },
    data: getInitializeConfigInstructionDataDecoder().decode(instruction.data),
  };
}
