/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findConfigPda, findMintAuthorityPda } from "../pdas";
import { PCN_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const OPEN_EPOCH_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  75, 57, 218, 33, 173, 254, 207, 136,
]);

export function getOpenEpochDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(OPEN_EPOCH_DISCRIMINATOR);
}

export type OpenEpochInstruction<
  TProgram extends string = typeof PCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountOracle extends string | AccountMeta<string> = string,
  TAccountFunder extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountEpoch extends string | AccountMeta<string> = string,
  TAccountEpochTokenVault extends string | AccountMeta<string> = string,
  TAccountMintAuthority extends string | AccountMeta<string> = string,
  TAccountRewardMint extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = "11111111111111111111111111111111",
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOracle extends string
        ? ReadonlySignerAccount<TAccountOracle> &
            AccountSignerMeta<TAccountOracle>
        : TAccountOracle,
      TAccountFunder extends string
        ? WritableSignerAccount<TAccountFunder> &
            AccountSignerMeta<TAccountFunder>
        : TAccountFunder,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountEpoch extends string
        ? WritableAccount<TAccountEpoch>
        : TAccountEpoch,
      TAccountEpochTokenVault extends string
        ? WritableAccount<TAccountEpochTokenVault>
        : TAccountEpochTokenVault,
      TAccountMintAuthority extends string
        ? ReadonlyAccount<TAccountMintAuthority>
        : TAccountMintAuthority,
      TAccountRewardMint extends string
        ? ReadonlyAccount<TAccountRewardMint>
        : TAccountRewardMint,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts
    ]
  >;

export type OpenEpochInstructionData = {
  discriminator: ReadonlyUint8Array;
  epochId: bigint;
  startSlot: bigint;
  endSlot: bigint;
  supportBudgetLamports: bigint;
};

export type OpenEpochInstructionDataArgs = {
  epochId: number | bigint;
  startSlot: number | bigint;
  endSlot: number | bigint;
  supportBudgetLamports: number | bigint;
};

export function getOpenEpochInstructionDataEncoder(): FixedSizeEncoder<OpenEpochInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["epochId", getU64Encoder()],
      ["startSlot", getU64Encoder()],
      ["endSlot", getU64Encoder()],
      ["supportBudgetLamports", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: OPEN_EPOCH_DISCRIMINATOR })
  );
}

export function getOpenEpochInstructionDataDecoder(): FixedSizeDecoder<OpenEpochInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["epochId", getU64Decoder()],
    ["startSlot", getU64Decoder()],
    ["endSlot", getU64Decoder()],
    ["supportBudgetLamports", getU64Decoder()],
  ]);
}

export function getOpenEpochInstructionDataCodec(): FixedSizeCodec<
  OpenEpochInstructionDataArgs,
  OpenEpochInstructionData
> {
  return combineCodec(
    getOpenEpochInstructionDataEncoder(),
    getOpenEpochInstructionDataDecoder()
  );
}

export type OpenEpochAsyncInput<
  TAccountOracle extends string = string,
  TAccountFunder extends string = string,
  TAccountConfig extends string = string,
  TAccountEpoch extends string = string,
  TAccountEpochTokenVault extends string = string,
  TAccountMintAuthority extends string = string,
  TAccountRewardMint extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string
> = {
  oracle: TransactionSigner<TAccountOracle>;
  funder: TransactionSigner<TAccountFunder>;
  config?: Address<TAccountConfig>;
  epoch: Address<TAccountEpoch>;
  epochTokenVault: Address<TAccountEpochTokenVault>;
  mintAuthority?: Address<TAccountMintAuthority>;
  rewardMint: Address<TAccountRewardMint>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  epochId: OpenEpochInstructionDataArgs["epochId"];
  startSlot: OpenEpochInstructionDataArgs["startSlot"];
  endSlot: OpenEpochInstructionDataArgs["endSlot"];
  supportBudgetLamports: OpenEpochInstructionDataArgs["supportBudgetLamports"];
};

export async function getOpenEpochInstructionAsync<
  TAccountOracle extends string,
  TAccountFunder extends string,
  TAccountConfig extends string,
  TAccountEpoch extends string,
  TAccountEpochTokenVault extends string,
  TAccountMintAuthority extends string,
  TAccountRewardMint extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof PCN_PROGRAM_PROGRAM_ADDRESS
>(
  input: OpenEpochAsyncInput<
    TAccountOracle,
    TAccountFunder,
    TAccountConfig,
    TAccountEpoch,
    TAccountEpochTokenVault,
    TAccountMintAuthority,
    TAccountRewardMint,
    TAccountSystemProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  OpenEpochInstruction<
    TProgramAddress,
    TAccountOracle,
    TAccountFunder,
    TAccountConfig,
    TAccountEpoch,
    TAccountEpochTokenVault,
    TAccountMintAuthority,
    TAccountRewardMint,
    TAccountSystemProgram,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    oracle: { value: input.oracle ?? null, isWritable: false },
    funder: { value: input.funder ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    epoch: { value: input.epoch ?? null, isWritable: true },
    epochTokenVault: { value: input.epochTokenVault ?? null, isWritable: true },
    mintAuthority: { value: input.mintAuthority ?? null, isWritable: false },
    rewardMint: { value: input.rewardMint ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.mintAuthority.value) {
    accounts.mintAuthority.value = await findMintAuthorityPda();
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("oracle", accounts.oracle),
      getAccountMeta("funder", accounts.funder),
      getAccountMeta("config", accounts.config),
      getAccountMeta("epoch", accounts.epoch),
      getAccountMeta("epochTokenVault", accounts.epochTokenVault),
      getAccountMeta("mintAuthority", accounts.mintAuthority),
      getAccountMeta("rewardMint", accounts.rewardMint),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getOpenEpochInstructionDataEncoder().encode(
      args as OpenEpochInstructionDataArgs
    ),
    programAddress,
  } as OpenEpochInstruction<TProgramAddress, TAccountOracle, TAccountFunder, TAccountConfig, TAccountEpoch, TAccountEpochTokenVault, TAccountMintAuthority, TAccountRewardMint, TAccountSystemProgram, TAccountTokenProgram>);
}

export type OpenEpochInput<
  TAccountOracle extends string = string,
  TAccountFunder extends string = string,
  TAccountConfig extends string = string,
  TAccountEpoch extends string = string,
  TAccountEpochTokenVault extends string = string,
  TAccountMintAuthority extends string = string,
  TAccountRewardMint extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string
> = {
  oracle: TransactionSigner<TAccountOracle>;
  funder: TransactionSigner<TAccountFunder>;
  config: Address<TAccountConfig>;
  epoch: Address<TAccountEpoch>;
  epochTokenVault: Address<TAccountEpochTokenVault>;
  mintAuthority: Address<TAccountMintAuthority>;
  rewardMint: Address<TAccountRewardMint>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  epochId: OpenEpochInstructionDataArgs["epochId"];
  startSlot: OpenEpochInstructionDataArgs["startSlot"];
  endSlot: OpenEpochInstructionDataArgs["endSlot"];
  supportBudgetLamports: OpenEpochInstructionDataArgs["supportBudgetLamports"];
};

export function getOpenEpochInstruction<
  TAccountOracle extends string,
  TAccountFunder extends string,
  TAccountConfig extends string,
  TAccountEpoch extends string,
  TAccountEpochTokenVault extends string,
  TAccountMintAuthority extends string,
  TAccountRewardMint extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof PCN_PROGRAM_PROGRAM_ADDRESS
>(
  input: OpenEpochInput<
    TAccountOracle,
    TAccountFunder,
    TAccountConfig,
    TAccountEpoch,
    TAccountEpochTokenVault,
    TAccountMintAuthority,
    TAccountRewardMint,
    TAccountSystemProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): OpenEpochInstruction<
  TProgramAddress,
  TAccountOracle,
  TAccountFunder,
  TAccountConfig,
  TAccountEpoch,
  TAccountEpochTokenVault,
  TAccountMintAuthority,
  TAccountRewardMint,
  TAccountSystemProgram,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? PCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    oracle: { value: input.oracle ?? null, isWritable: false },
    funder: { value: input.funder ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    epoch: { value: input.epoch ?? null, isWritable: true },
    epochTokenVault: { value: input.epochTokenVault ?? null, isWritable: true },
    mintAuthority: { value: input.mintAuthority ?? null, isWritable: false },
    rewardMint: { value: input.rewardMint ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("oracle", accounts.oracle),
      getAccountMeta("funder", accounts.funder),
      getAccountMeta("config", accounts.config),
      getAccountMeta("epoch", accounts.epoch),
      getAccountMeta("epochTokenVault", accounts.epochTokenVault),
      getAccountMeta("mintAuthority", accounts.mintAuthority),
      getAccountMeta("rewardMint", accounts.rewardMint),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getOpenEpochInstructionDataEncoder().encode(
      args as OpenEpochInstructionDataArgs
    ),
    programAddress,
  } as OpenEpochInstruction<TProgramAddress, TAccountOracle, TAccountFunder, TAccountConfig, TAccountEpoch, TAccountEpochTokenVault, TAccountMintAuthority, TAccountRewardMint, TAccountSystemProgram, TAccountTokenProgram>);
}

export type ParsedOpenEpochInstruction<
  TProgram extends string = typeof PCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
  programAddress: Address<TProgram>;
  accounts: {
    oracle: TAccountMetas[0];
    funder: TAccountMetas[1];
    config: TAccountMetas[2];
    epoch: TAccountMetas[3];
    epochTokenVault: TAccountMetas[4];
    mintAuthority: TAccountMetas[5];
    rewardMint: TAccountMetas[6];
    systemProgram: TAccountMetas[7];
    tokenProgram: TAccountMetas[8];
  };
  data: OpenEpochInstructionData;
};

export function parseOpenEpochInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[]
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedOpenEpochInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 9,
      }
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      oracle: getNextAccount(),
      funder: getNextAccount(),
      config: getNextAccount(),
      epoch: getNextAccount(),
      epochTokenVault: getNextAccount(),
      mintAuthority: getNextAccount(),
      rewardMint: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getOpenEpochInstructionDataDecoder().decode(instruction.data),
  };
}
