/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findConfigPda, findMintAuthorityPda } from "../pdas";
import { PCN_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const SWEEP_EPOCH_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  187, 9, 52, 111, 60, 24, 52, 28,
]);

export function getSweepEpochDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(SWEEP_EPOCH_DISCRIMINATOR);
}

export type SweepEpochInstruction<
  TProgram extends string = typeof PCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountOracle extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountEpoch extends string | AccountMeta<string> = string,
  TAccountEpochTokenVault extends string | AccountMeta<string> = string,
  TAccountTokenReserveVault extends string | AccountMeta<string> = string,
  TAccountMintAuthority extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOracle extends string
        ? ReadonlySignerAccount<TAccountOracle> &
            AccountSignerMeta<TAccountOracle>
        : TAccountOracle,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountEpoch extends string
        ? WritableAccount<TAccountEpoch>
        : TAccountEpoch,
      TAccountEpochTokenVault extends string
        ? WritableAccount<TAccountEpochTokenVault>
        : TAccountEpochTokenVault,
      TAccountTokenReserveVault extends string
        ? WritableAccount<TAccountTokenReserveVault>
        : TAccountTokenReserveVault,
      TAccountMintAuthority extends string
        ? ReadonlyAccount<TAccountMintAuthority>
        : TAccountMintAuthority,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts
    ]
  >;

export type SweepEpochInstructionData = {
  discriminator: ReadonlyUint8Array;
  epochId: bigint;
};

export type SweepEpochInstructionDataArgs = { epochId: number | bigint };

export function getSweepEpochInstructionDataEncoder(): FixedSizeEncoder<SweepEpochInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["epochId", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SWEEP_EPOCH_DISCRIMINATOR })
  );
}

export function getSweepEpochInstructionDataDecoder(): FixedSizeDecoder<SweepEpochInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["epochId", getU64Decoder()],
  ]);
}

export function getSweepEpochInstructionDataCodec(): FixedSizeCodec<
  SweepEpochInstructionDataArgs,
  SweepEpochInstructionData
> {
  return combineCodec(
    getSweepEpochInstructionDataEncoder(),
    getSweepEpochInstructionDataDecoder()
  );
}

export type SweepEpochAsyncInput<
  TAccountOracle extends string = string,
  TAccountConfig extends string = string,
  TAccountEpoch extends string = string,
  TAccountEpochTokenVault extends string = string,
  TAccountTokenReserveVault extends string = string,
  TAccountMintAuthority extends string = string,
  TAccountTokenProgram extends string = string
> = {
  oracle: TransactionSigner<TAccountOracle>;
  config?: Address<TAccountConfig>;
  epoch: Address<TAccountEpoch>;
  epochTokenVault: Address<TAccountEpochTokenVault>;
  tokenReserveVault: Address<TAccountTokenReserveVault>;
  mintAuthority?: Address<TAccountMintAuthority>;
  tokenProgram?: Address<TAccountTokenProgram>;
  epochId: SweepEpochInstructionDataArgs["epochId"];
};

export async function getSweepEpochInstructionAsync<
  TAccountOracle extends string,
  TAccountConfig extends string,
  TAccountEpoch extends string,
  TAccountEpochTokenVault extends string,
  TAccountTokenReserveVault extends string,
  TAccountMintAuthority extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof PCN_PROGRAM_PROGRAM_ADDRESS
>(
  input: SweepEpochAsyncInput<
    TAccountOracle,
    TAccountConfig,
    TAccountEpoch,
    TAccountEpochTokenVault,
    TAccountTokenReserveVault,
    TAccountMintAuthority,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  SweepEpochInstruction<
    TProgramAddress,
    TAccountOracle,
    TAccountConfig,
    TAccountEpoch,
    TAccountEpochTokenVault,
    TAccountTokenReserveVault,
    TAccountMintAuthority,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? PCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    oracle: { value: input.oracle ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    epoch: { value: input.epoch ?? null, isWritable: true },
    epochTokenVault: { value: input.epochTokenVault ?? null, isWritable: true },
    tokenReserveVault: {
      value: input.tokenReserveVault ?? null,
      isWritable: true,
    },
    mintAuthority: { value: input.mintAuthority ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.mintAuthority.value) {
    accounts.mintAuthority.value = await findMintAuthorityPda();
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("oracle", accounts.oracle),
      getAccountMeta("config", accounts.config),
      getAccountMeta("epoch", accounts.epoch),
      getAccountMeta("epochTokenVault", accounts.epochTokenVault),
      getAccountMeta("tokenReserveVault", accounts.tokenReserveVault),
      getAccountMeta("mintAuthority", accounts.mintAuthority),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getSweepEpochInstructionDataEncoder().encode(
      args as SweepEpochInstructionDataArgs
    ),
    programAddress,
  } as SweepEpochInstruction<TProgramAddress, TAccountOracle, TAccountConfig, TAccountEpoch, TAccountEpochTokenVault, TAccountTokenReserveVault, TAccountMintAuthority, TAccountTokenProgram>);
}

export type SweepEpochInput<
  TAccountOracle extends string = string,
  TAccountConfig extends string = string,
  TAccountEpoch extends string = string,
  TAccountEpochTokenVault extends string = string,
  TAccountTokenReserveVault extends string = string,
  TAccountMintAuthority extends string = string,
  TAccountTokenProgram extends string = string
> = {
  oracle: TransactionSigner<TAccountOracle>;
  config: Address<TAccountConfig>;
  epoch: Address<TAccountEpoch>;
  epochTokenVault: Address<TAccountEpochTokenVault>;
  tokenReserveVault: Address<TAccountTokenReserveVault>;
  mintAuthority: Address<TAccountMintAuthority>;
  tokenProgram?: Address<TAccountTokenProgram>;
  epochId: SweepEpochInstructionDataArgs["epochId"];
};

export function getSweepEpochInstruction<
  TAccountOracle extends string,
  TAccountConfig extends string,
  TAccountEpoch extends string,
  TAccountEpochTokenVault extends string,
  TAccountTokenReserveVault extends string,
  TAccountMintAuthority extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof PCN_PROGRAM_PROGRAM_ADDRESS
>(
  input: SweepEpochInput<
    TAccountOracle,
    TAccountConfig,
    TAccountEpoch,
    TAccountEpochTokenVault,
    TAccountTokenReserveVault,
    TAccountMintAuthority,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): SweepEpochInstruction<
  TProgramAddress,
  TAccountOracle,
  TAccountConfig,
  TAccountEpoch,
  TAccountEpochTokenVault,
  TAccountTokenReserveVault,
  TAccountMintAuthority,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? PCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    oracle: { value: input.oracle ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    epoch: { value: input.epoch ?? null, isWritable: true },
    epochTokenVault: { value: input.epochTokenVault ?? null, isWritable: true },
    tokenReserveVault: {
      value: input.tokenReserveVault ?? null,
      isWritable: true,
    },
    mintAuthority: { value: input.mintAuthority ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("oracle", accounts.oracle),
      getAccountMeta("config", accounts.config),
      getAccountMeta("epoch", accounts.epoch),
      getAccountMeta("epochTokenVault", accounts.epochTokenVault),
      getAccountMeta("tokenReserveVault", accounts.tokenReserveVault),
      getAccountMeta("mintAuthority", accounts.mintAuthority),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getSweepEpochInstructionDataEncoder().encode(
      args as SweepEpochInstructionDataArgs
    ),
    programAddress,
  } as SweepEpochInstruction<TProgramAddress, TAccountOracle, TAccountConfig, TAccountEpoch, TAccountEpochTokenVault, TAccountTokenReserveVault, TAccountMintAuthority, TAccountTokenProgram>);
}

export type ParsedSweepEpochInstruction<
  TProgram extends string = typeof PCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
  programAddress: Address<TProgram>;
  accounts: {
    oracle: TAccountMetas[0];
    config: TAccountMetas[1];
    epoch: TAccountMetas[2];
    epochTokenVault: TAccountMetas[3];
    tokenReserveVault: TAccountMetas[4];
    mintAuthority: TAccountMetas[5];
    tokenProgram: TAccountMetas[6];
  };
  data: SweepEpochInstructionData;
};

export function parseSweepEpochInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[]
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedSweepEpochInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 7,
      }
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      oracle: getNextAccount(),
      config: getNextAccount(),
      epoch: getNextAccount(),
      epochTokenVault: getNextAccount(),
      tokenReserveVault: getNextAccount(),
      mintAuthority: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getSweepEpochInstructionDataDecoder().decode(instruction.data),
  };
}
