//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const CLAIM_REWARD_DISCRIMINATOR: [u8; 8] = [149, 95, 181, 242, 94, 90, 158, 162];

/// Accounts.
#[derive(Debug)]
pub struct ClaimReward {
    pub user: solana_address::Address,

    pub config: solana_address::Address,

    pub epoch: solana_address::Address,

    pub claim: solana_address::Address,

    pub epoch_token_vault: solana_address::Address,

    pub user_token_account: solana_address::Address,

    pub mint_authority: solana_address::Address,

    pub token_program: solana_address::Address,
}

impl ClaimReward {
    pub fn instruction(&self, args: ClaimRewardInstructionArgs) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: ClaimRewardInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(8 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.user, true,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.epoch, false));
        accounts.push(solana_instruction::AccountMeta::new(self.claim, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.epoch_token_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.user_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.mint_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = ClaimRewardInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::PCN_PROGRAM_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct ClaimRewardInstructionData {
    discriminator: [u8; 8],
}

impl ClaimRewardInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [149, 95, 181, 242, 94, 90, 158, 162],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for ClaimRewardInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct ClaimRewardInstructionArgs {
    pub epoch_id: u64,
}

impl ClaimRewardInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `ClaimReward`.
///
/// ### Accounts:
///
///   0. `[signer]` user
///   1. `[]` config
///   2. `[writable]` epoch
///   3. `[writable]` claim
///   4. `[writable]` epoch_token_vault
///   5. `[writable]` user_token_account
///   6. `[]` mint_authority
///   7. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
#[derive(Clone, Debug, Default)]
pub struct ClaimRewardBuilder {
    user: Option<solana_address::Address>,
    config: Option<solana_address::Address>,
    epoch: Option<solana_address::Address>,
    claim: Option<solana_address::Address>,
    epoch_token_vault: Option<solana_address::Address>,
    user_token_account: Option<solana_address::Address>,
    mint_authority: Option<solana_address::Address>,
    token_program: Option<solana_address::Address>,
    epoch_id: Option<u64>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl ClaimRewardBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn user(&mut self, user: solana_address::Address) -> &mut Self {
        self.user = Some(user);
        self
    }
    #[inline(always)]
    pub fn config(&mut self, config: solana_address::Address) -> &mut Self {
        self.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn epoch(&mut self, epoch: solana_address::Address) -> &mut Self {
        self.epoch = Some(epoch);
        self
    }
    #[inline(always)]
    pub fn claim(&mut self, claim: solana_address::Address) -> &mut Self {
        self.claim = Some(claim);
        self
    }
    #[inline(always)]
    pub fn epoch_token_vault(&mut self, epoch_token_vault: solana_address::Address) -> &mut Self {
        self.epoch_token_vault = Some(epoch_token_vault);
        self
    }
    #[inline(always)]
    pub fn user_token_account(&mut self, user_token_account: solana_address::Address) -> &mut Self {
        self.user_token_account = Some(user_token_account);
        self
    }
    #[inline(always)]
    pub fn mint_authority(&mut self, mint_authority: solana_address::Address) -> &mut Self {
        self.mint_authority = Some(mint_authority);
        self
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_address::Address) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn epoch_id(&mut self, epoch_id: u64) -> &mut Self {
        self.epoch_id = Some(epoch_id);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = ClaimReward {
            user: self.user.expect("user is not set"),
            config: self.config.expect("config is not set"),
            epoch: self.epoch.expect("epoch is not set"),
            claim: self.claim.expect("claim is not set"),
            epoch_token_vault: self
                .epoch_token_vault
                .expect("epoch_token_vault is not set"),
            user_token_account: self
                .user_token_account
                .expect("user_token_account is not set"),
            mint_authority: self.mint_authority.expect("mint_authority is not set"),
            token_program: self.token_program.unwrap_or(solana_address::address!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
        };
        let args = ClaimRewardInstructionArgs {
            epoch_id: self.epoch_id.clone().expect("epoch_id is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `claim_reward` CPI accounts.
pub struct ClaimRewardCpiAccounts<'a, 'b> {
    pub user: &'b solana_account_info::AccountInfo<'a>,

    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub epoch: &'b solana_account_info::AccountInfo<'a>,

    pub claim: &'b solana_account_info::AccountInfo<'a>,

    pub epoch_token_vault: &'b solana_account_info::AccountInfo<'a>,

    pub user_token_account: &'b solana_account_info::AccountInfo<'a>,

    pub mint_authority: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `claim_reward` CPI instruction.
pub struct ClaimRewardCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub user: &'b solana_account_info::AccountInfo<'a>,

    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub epoch: &'b solana_account_info::AccountInfo<'a>,

    pub claim: &'b solana_account_info::AccountInfo<'a>,

    pub epoch_token_vault: &'b solana_account_info::AccountInfo<'a>,

    pub user_token_account: &'b solana_account_info::AccountInfo<'a>,

    pub mint_authority: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: ClaimRewardInstructionArgs,
}

impl<'a, 'b> ClaimRewardCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: ClaimRewardCpiAccounts<'a, 'b>,
        args: ClaimRewardInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            user: accounts.user,
            config: accounts.config,
            epoch: accounts.epoch,
            claim: accounts.claim,
            epoch_token_vault: accounts.epoch_token_vault,
            user_token_account: accounts.user_token_account,
            mint_authority: accounts.mint_authority,
            token_program: accounts.token_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(8 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.user.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.epoch.key, false));
        accounts.push(solana_instruction::AccountMeta::new(*self.claim.key, false));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.epoch_token_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.user_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.mint_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = ClaimRewardInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::PCN_PROGRAM_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(9 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.user.clone());
        account_infos.push(self.config.clone());
        account_infos.push(self.epoch.clone());
        account_infos.push(self.claim.clone());
        account_infos.push(self.epoch_token_vault.clone());
        account_infos.push(self.user_token_account.clone());
        account_infos.push(self.mint_authority.clone());
        account_infos.push(self.token_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `ClaimReward` via CPI.
///
/// ### Accounts:
///
///   0. `[signer]` user
///   1. `[]` config
///   2. `[writable]` epoch
///   3. `[writable]` claim
///   4. `[writable]` epoch_token_vault
///   5. `[writable]` user_token_account
///   6. `[]` mint_authority
///   7. `[]` token_program
#[derive(Clone, Debug)]
pub struct ClaimRewardCpiBuilder<'a, 'b> {
    instruction: Box<ClaimRewardCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> ClaimRewardCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(ClaimRewardCpiBuilderInstruction {
            __program: program,
            user: None,
            config: None,
            epoch: None,
            claim: None,
            epoch_token_vault: None,
            user_token_account: None,
            mint_authority: None,
            token_program: None,
            epoch_id: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn user(&mut self, user: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.user = Some(user);
        self
    }
    #[inline(always)]
    pub fn config(&mut self, config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn epoch(&mut self, epoch: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.epoch = Some(epoch);
        self
    }
    #[inline(always)]
    pub fn claim(&mut self, claim: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.claim = Some(claim);
        self
    }
    #[inline(always)]
    pub fn epoch_token_vault(
        &mut self,
        epoch_token_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.epoch_token_vault = Some(epoch_token_vault);
        self
    }
    #[inline(always)]
    pub fn user_token_account(
        &mut self,
        user_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.user_token_account = Some(user_token_account);
        self
    }
    #[inline(always)]
    pub fn mint_authority(
        &mut self,
        mint_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.mint_authority = Some(mint_authority);
        self
    }
    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn epoch_id(&mut self, epoch_id: u64) -> &mut Self {
        self.instruction.epoch_id = Some(epoch_id);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = ClaimRewardInstructionArgs {
            epoch_id: self
                .instruction
                .epoch_id
                .clone()
                .expect("epoch_id is not set"),
        };
        let instruction = ClaimRewardCpi {
            __program: self.instruction.__program,

            user: self.instruction.user.expect("user is not set"),

            config: self.instruction.config.expect("config is not set"),

            epoch: self.instruction.epoch.expect("epoch is not set"),

            claim: self.instruction.claim.expect("claim is not set"),

            epoch_token_vault: self
                .instruction
                .epoch_token_vault
                .expect("epoch_token_vault is not set"),

            user_token_account: self
                .instruction
                .user_token_account
                .expect("user_token_account is not set"),

            mint_authority: self
                .instruction
                .mint_authority
                .expect("mint_authority is not set"),

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct ClaimRewardCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    user: Option<&'b solana_account_info::AccountInfo<'a>>,
    config: Option<&'b solana_account_info::AccountInfo<'a>>,
    epoch: Option<&'b solana_account_info::AccountInfo<'a>>,
    claim: Option<&'b solana_account_info::AccountInfo<'a>>,
    epoch_token_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    user_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    mint_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    epoch_id: Option<u64>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
