//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::codama_rust::types::PerformanceMetrics;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_address::Address;

pub const CREATE_CLAIM_DISCRIMINATOR: [u8; 8] = [71, 122, 43, 84, 240, 165, 215, 181];

/// Accounts.
#[derive(Debug)]
pub struct CreateClaim {
    pub oracle: solana_address::Address,

    pub payer: solana_address::Address,

    pub config: solana_address::Address,

    pub epoch: solana_address::Address,

    pub claim: solana_address::Address,

    pub system_program: solana_address::Address,
}

impl CreateClaim {
    pub fn instruction(&self, args: CreateClaimInstructionArgs) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: CreateClaimInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(6 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.oracle,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.payer, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.epoch, false));
        accounts.push(solana_instruction::AccountMeta::new(self.claim, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = CreateClaimInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::PCN_PROGRAM_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct CreateClaimInstructionData {
    discriminator: [u8; 8],
}

impl CreateClaimInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [71, 122, 43, 84, 240, 165, 215, 181],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for CreateClaimInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct CreateClaimInstructionArgs {
    pub epoch_id: u64,
    pub user: Address,
    pub performance: PerformanceMetrics,
}

impl CreateClaimInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `CreateClaim`.
///
/// ### Accounts:
///
///   0. `[signer]` oracle
///   1. `[writable, signer]` payer
///   2. `[]` config
///   3. `[writable]` epoch
///   4. `[writable]` claim
///   5. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct CreateClaimBuilder {
    oracle: Option<solana_address::Address>,
    payer: Option<solana_address::Address>,
    config: Option<solana_address::Address>,
    epoch: Option<solana_address::Address>,
    claim: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    epoch_id: Option<u64>,
    user: Option<Address>,
    performance: Option<PerformanceMetrics>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl CreateClaimBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn oracle(&mut self, oracle: solana_address::Address) -> &mut Self {
        self.oracle = Some(oracle);
        self
    }
    #[inline(always)]
    pub fn payer(&mut self, payer: solana_address::Address) -> &mut Self {
        self.payer = Some(payer);
        self
    }
    #[inline(always)]
    pub fn config(&mut self, config: solana_address::Address) -> &mut Self {
        self.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn epoch(&mut self, epoch: solana_address::Address) -> &mut Self {
        self.epoch = Some(epoch);
        self
    }
    #[inline(always)]
    pub fn claim(&mut self, claim: solana_address::Address) -> &mut Self {
        self.claim = Some(claim);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn epoch_id(&mut self, epoch_id: u64) -> &mut Self {
        self.epoch_id = Some(epoch_id);
        self
    }
    #[inline(always)]
    pub fn user(&mut self, user: Address) -> &mut Self {
        self.user = Some(user);
        self
    }
    #[inline(always)]
    pub fn performance(&mut self, performance: PerformanceMetrics) -> &mut Self {
        self.performance = Some(performance);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = CreateClaim {
            oracle: self.oracle.expect("oracle is not set"),
            payer: self.payer.expect("payer is not set"),
            config: self.config.expect("config is not set"),
            epoch: self.epoch.expect("epoch is not set"),
            claim: self.claim.expect("claim is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
        };
        let args = CreateClaimInstructionArgs {
            epoch_id: self.epoch_id.clone().expect("epoch_id is not set"),
            user: self.user.clone().expect("user is not set"),
            performance: self.performance.clone().expect("performance is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `create_claim` CPI accounts.
pub struct CreateClaimCpiAccounts<'a, 'b> {
    pub oracle: &'b solana_account_info::AccountInfo<'a>,

    pub payer: &'b solana_account_info::AccountInfo<'a>,

    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub epoch: &'b solana_account_info::AccountInfo<'a>,

    pub claim: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `create_claim` CPI instruction.
pub struct CreateClaimCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub oracle: &'b solana_account_info::AccountInfo<'a>,

    pub payer: &'b solana_account_info::AccountInfo<'a>,

    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub epoch: &'b solana_account_info::AccountInfo<'a>,

    pub claim: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: CreateClaimInstructionArgs,
}

impl<'a, 'b> CreateClaimCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: CreateClaimCpiAccounts<'a, 'b>,
        args: CreateClaimInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            oracle: accounts.oracle,
            payer: accounts.payer,
            config: accounts.config,
            epoch: accounts.epoch,
            claim: accounts.claim,
            system_program: accounts.system_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(6 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.oracle.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.payer.key, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.epoch.key, false));
        accounts.push(solana_instruction::AccountMeta::new(*self.claim.key, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = CreateClaimInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::PCN_PROGRAM_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(7 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.oracle.clone());
        account_infos.push(self.payer.clone());
        account_infos.push(self.config.clone());
        account_infos.push(self.epoch.clone());
        account_infos.push(self.claim.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `CreateClaim` via CPI.
///
/// ### Accounts:
///
///   0. `[signer]` oracle
///   1. `[writable, signer]` payer
///   2. `[]` config
///   3. `[writable]` epoch
///   4. `[writable]` claim
///   5. `[]` system_program
#[derive(Clone, Debug)]
pub struct CreateClaimCpiBuilder<'a, 'b> {
    instruction: Box<CreateClaimCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> CreateClaimCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(CreateClaimCpiBuilderInstruction {
            __program: program,
            oracle: None,
            payer: None,
            config: None,
            epoch: None,
            claim: None,
            system_program: None,
            epoch_id: None,
            user: None,
            performance: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn oracle(&mut self, oracle: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.oracle = Some(oracle);
        self
    }
    #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.payer = Some(payer);
        self
    }
    #[inline(always)]
    pub fn config(&mut self, config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn epoch(&mut self, epoch: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.epoch = Some(epoch);
        self
    }
    #[inline(always)]
    pub fn claim(&mut self, claim: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.claim = Some(claim);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn epoch_id(&mut self, epoch_id: u64) -> &mut Self {
        self.instruction.epoch_id = Some(epoch_id);
        self
    }
    #[inline(always)]
    pub fn user(&mut self, user: Address) -> &mut Self {
        self.instruction.user = Some(user);
        self
    }
    #[inline(always)]
    pub fn performance(&mut self, performance: PerformanceMetrics) -> &mut Self {
        self.instruction.performance = Some(performance);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = CreateClaimInstructionArgs {
            epoch_id: self
                .instruction
                .epoch_id
                .clone()
                .expect("epoch_id is not set"),
            user: self.instruction.user.clone().expect("user is not set"),
            performance: self
                .instruction
                .performance
                .clone()
                .expect("performance is not set"),
        };
        let instruction = CreateClaimCpi {
            __program: self.instruction.__program,

            oracle: self.instruction.oracle.expect("oracle is not set"),

            payer: self.instruction.payer.expect("payer is not set"),

            config: self.instruction.config.expect("config is not set"),

            epoch: self.instruction.epoch.expect("epoch is not set"),

            claim: self.instruction.claim.expect("claim is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct CreateClaimCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    oracle: Option<&'b solana_account_info::AccountInfo<'a>>,
    payer: Option<&'b solana_account_info::AccountInfo<'a>>,
    config: Option<&'b solana_account_info::AccountInfo<'a>>,
    epoch: Option<&'b solana_account_info::AccountInfo<'a>>,
    claim: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    epoch_id: Option<u64>,
    user: Option<Address>,
    performance: Option<PerformanceMetrics>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
