//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const FINALIZE_EPOCH_DISCRIMINATOR: [u8; 8] = [159, 93, 117, 217, 63, 44, 249, 76];

/// Accounts.
#[derive(Debug)]
pub struct FinalizeEpoch {
    pub oracle: solana_address::Address,

    pub refund_target: solana_address::Address,

    pub config: solana_address::Address,

    pub epoch: solana_address::Address,

    pub epoch_token_vault: solana_address::Address,

    pub reward_mint: solana_address::Address,

    pub mint_authority: solana_address::Address,

    pub sol_reserve: solana_address::Address,

    pub token_program: solana_address::Address,

    pub system_program: solana_address::Address,
}

impl FinalizeEpoch {
    pub fn instruction(
        &self,
        args: FinalizeEpochInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: FinalizeEpochInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(10 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.oracle,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.refund_target,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.config, false));
        accounts.push(solana_instruction::AccountMeta::new(self.epoch, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.epoch_token_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.reward_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.mint_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.sol_reserve,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = FinalizeEpochInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::PCN_PROGRAM_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct FinalizeEpochInstructionData {
    discriminator: [u8; 8],
}

impl FinalizeEpochInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [159, 93, 117, 217, 63, 44, 249, 76],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for FinalizeEpochInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct FinalizeEpochInstructionArgs {
    pub total_reward_weight: u64,
}

impl FinalizeEpochInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `FinalizeEpoch`.
///
/// ### Accounts:
///
///   0. `[signer]` oracle
///   1. `[writable]` refund_target
///   2. `[writable]` config
///   3. `[writable]` epoch
///   4. `[writable]` epoch_token_vault
///   5. `[writable]` reward_mint
///   6. `[]` mint_authority
///   7. `[writable]` sol_reserve
///   8. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
///   9. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct FinalizeEpochBuilder {
    oracle: Option<solana_address::Address>,
    refund_target: Option<solana_address::Address>,
    config: Option<solana_address::Address>,
    epoch: Option<solana_address::Address>,
    epoch_token_vault: Option<solana_address::Address>,
    reward_mint: Option<solana_address::Address>,
    mint_authority: Option<solana_address::Address>,
    sol_reserve: Option<solana_address::Address>,
    token_program: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    total_reward_weight: Option<u64>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl FinalizeEpochBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn oracle(&mut self, oracle: solana_address::Address) -> &mut Self {
        self.oracle = Some(oracle);
        self
    }
    #[inline(always)]
    pub fn refund_target(&mut self, refund_target: solana_address::Address) -> &mut Self {
        self.refund_target = Some(refund_target);
        self
    }
    #[inline(always)]
    pub fn config(&mut self, config: solana_address::Address) -> &mut Self {
        self.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn epoch(&mut self, epoch: solana_address::Address) -> &mut Self {
        self.epoch = Some(epoch);
        self
    }
    #[inline(always)]
    pub fn epoch_token_vault(&mut self, epoch_token_vault: solana_address::Address) -> &mut Self {
        self.epoch_token_vault = Some(epoch_token_vault);
        self
    }
    #[inline(always)]
    pub fn reward_mint(&mut self, reward_mint: solana_address::Address) -> &mut Self {
        self.reward_mint = Some(reward_mint);
        self
    }
    #[inline(always)]
    pub fn mint_authority(&mut self, mint_authority: solana_address::Address) -> &mut Self {
        self.mint_authority = Some(mint_authority);
        self
    }
    #[inline(always)]
    pub fn sol_reserve(&mut self, sol_reserve: solana_address::Address) -> &mut Self {
        self.sol_reserve = Some(sol_reserve);
        self
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_address::Address) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn total_reward_weight(&mut self, total_reward_weight: u64) -> &mut Self {
        self.total_reward_weight = Some(total_reward_weight);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = FinalizeEpoch {
            oracle: self.oracle.expect("oracle is not set"),
            refund_target: self.refund_target.expect("refund_target is not set"),
            config: self.config.expect("config is not set"),
            epoch: self.epoch.expect("epoch is not set"),
            epoch_token_vault: self
                .epoch_token_vault
                .expect("epoch_token_vault is not set"),
            reward_mint: self.reward_mint.expect("reward_mint is not set"),
            mint_authority: self.mint_authority.expect("mint_authority is not set"),
            sol_reserve: self.sol_reserve.expect("sol_reserve is not set"),
            token_program: self.token_program.unwrap_or(solana_address::address!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
        };
        let args = FinalizeEpochInstructionArgs {
            total_reward_weight: self
                .total_reward_weight
                .clone()
                .expect("total_reward_weight is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `finalize_epoch` CPI accounts.
pub struct FinalizeEpochCpiAccounts<'a, 'b> {
    pub oracle: &'b solana_account_info::AccountInfo<'a>,

    pub refund_target: &'b solana_account_info::AccountInfo<'a>,

    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub epoch: &'b solana_account_info::AccountInfo<'a>,

    pub epoch_token_vault: &'b solana_account_info::AccountInfo<'a>,

    pub reward_mint: &'b solana_account_info::AccountInfo<'a>,

    pub mint_authority: &'b solana_account_info::AccountInfo<'a>,

    pub sol_reserve: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `finalize_epoch` CPI instruction.
pub struct FinalizeEpochCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub oracle: &'b solana_account_info::AccountInfo<'a>,

    pub refund_target: &'b solana_account_info::AccountInfo<'a>,

    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub epoch: &'b solana_account_info::AccountInfo<'a>,

    pub epoch_token_vault: &'b solana_account_info::AccountInfo<'a>,

    pub reward_mint: &'b solana_account_info::AccountInfo<'a>,

    pub mint_authority: &'b solana_account_info::AccountInfo<'a>,

    pub sol_reserve: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: FinalizeEpochInstructionArgs,
}

impl<'a, 'b> FinalizeEpochCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: FinalizeEpochCpiAccounts<'a, 'b>,
        args: FinalizeEpochInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            oracle: accounts.oracle,
            refund_target: accounts.refund_target,
            config: accounts.config,
            epoch: accounts.epoch,
            epoch_token_vault: accounts.epoch_token_vault,
            reward_mint: accounts.reward_mint,
            mint_authority: accounts.mint_authority,
            sol_reserve: accounts.sol_reserve,
            token_program: accounts.token_program,
            system_program: accounts.system_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(10 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.oracle.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.refund_target.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.epoch.key, false));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.epoch_token_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.reward_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.mint_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.sol_reserve.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = FinalizeEpochInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::PCN_PROGRAM_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(11 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.oracle.clone());
        account_infos.push(self.refund_target.clone());
        account_infos.push(self.config.clone());
        account_infos.push(self.epoch.clone());
        account_infos.push(self.epoch_token_vault.clone());
        account_infos.push(self.reward_mint.clone());
        account_infos.push(self.mint_authority.clone());
        account_infos.push(self.sol_reserve.clone());
        account_infos.push(self.token_program.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `FinalizeEpoch` via CPI.
///
/// ### Accounts:
///
///   0. `[signer]` oracle
///   1. `[writable]` refund_target
///   2. `[writable]` config
///   3. `[writable]` epoch
///   4. `[writable]` epoch_token_vault
///   5. `[writable]` reward_mint
///   6. `[]` mint_authority
///   7. `[writable]` sol_reserve
///   8. `[]` token_program
///   9. `[]` system_program
#[derive(Clone, Debug)]
pub struct FinalizeEpochCpiBuilder<'a, 'b> {
    instruction: Box<FinalizeEpochCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> FinalizeEpochCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(FinalizeEpochCpiBuilderInstruction {
            __program: program,
            oracle: None,
            refund_target: None,
            config: None,
            epoch: None,
            epoch_token_vault: None,
            reward_mint: None,
            mint_authority: None,
            sol_reserve: None,
            token_program: None,
            system_program: None,
            total_reward_weight: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn oracle(&mut self, oracle: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.oracle = Some(oracle);
        self
    }
    #[inline(always)]
    pub fn refund_target(
        &mut self,
        refund_target: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.refund_target = Some(refund_target);
        self
    }
    #[inline(always)]
    pub fn config(&mut self, config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn epoch(&mut self, epoch: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.epoch = Some(epoch);
        self
    }
    #[inline(always)]
    pub fn epoch_token_vault(
        &mut self,
        epoch_token_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.epoch_token_vault = Some(epoch_token_vault);
        self
    }
    #[inline(always)]
    pub fn reward_mint(
        &mut self,
        reward_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.reward_mint = Some(reward_mint);
        self
    }
    #[inline(always)]
    pub fn mint_authority(
        &mut self,
        mint_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.mint_authority = Some(mint_authority);
        self
    }
    #[inline(always)]
    pub fn sol_reserve(
        &mut self,
        sol_reserve: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.sol_reserve = Some(sol_reserve);
        self
    }
    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn total_reward_weight(&mut self, total_reward_weight: u64) -> &mut Self {
        self.instruction.total_reward_weight = Some(total_reward_weight);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = FinalizeEpochInstructionArgs {
            total_reward_weight: self
                .instruction
                .total_reward_weight
                .clone()
                .expect("total_reward_weight is not set"),
        };
        let instruction = FinalizeEpochCpi {
            __program: self.instruction.__program,

            oracle: self.instruction.oracle.expect("oracle is not set"),

            refund_target: self
                .instruction
                .refund_target
                .expect("refund_target is not set"),

            config: self.instruction.config.expect("config is not set"),

            epoch: self.instruction.epoch.expect("epoch is not set"),

            epoch_token_vault: self
                .instruction
                .epoch_token_vault
                .expect("epoch_token_vault is not set"),

            reward_mint: self
                .instruction
                .reward_mint
                .expect("reward_mint is not set"),

            mint_authority: self
                .instruction
                .mint_authority
                .expect("mint_authority is not set"),

            sol_reserve: self
                .instruction
                .sol_reserve
                .expect("sol_reserve is not set"),

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct FinalizeEpochCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    oracle: Option<&'b solana_account_info::AccountInfo<'a>>,
    refund_target: Option<&'b solana_account_info::AccountInfo<'a>>,
    config: Option<&'b solana_account_info::AccountInfo<'a>>,
    epoch: Option<&'b solana_account_info::AccountInfo<'a>>,
    epoch_token_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    reward_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    mint_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    sol_reserve: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    total_reward_weight: Option<u64>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
