//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::codama_rust::types::CurveParams;
use crate::codama_rust::types::PerformanceWeights;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_address::Address;

pub const INITIALIZE_CONFIG_DISCRIMINATOR: [u8; 8] = [208, 127, 21, 1, 194, 190, 196, 70];

/// Accounts.
#[derive(Debug)]
pub struct InitializeConfig {
    pub payer: solana_address::Address,

    pub program: solana_address::Address,

    pub program_data: solana_address::Address,

    pub config: solana_address::Address,

    pub reward_mint: solana_address::Address,

    pub mint_authority: solana_address::Address,

    pub sol_reserve: solana_address::Address,

    pub token_reserve_vault: solana_address::Address,

    pub system_program: solana_address::Address,

    pub token_program: solana_address::Address,
}

impl InitializeConfig {
    pub fn instruction(
        &self,
        args: InitializeConfigInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: InitializeConfigInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(10 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.payer, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.program_data,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.config, false));
        accounts.push(solana_instruction::AccountMeta::new(self.reward_mint, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.mint_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.sol_reserve,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_reserve_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = InitializeConfigInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::PCN_PROGRAM_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct InitializeConfigInstructionData {
    discriminator: [u8; 8],
}

impl InitializeConfigInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [208, 127, 21, 1, 194, 190, 196, 70],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for InitializeConfigInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct InitializeConfigInstructionArgs {
    pub admin: Address,
    pub oracle: Address,
    pub claim_window_slots: u64,
    pub curve: CurveParams,
    pub performance_weights: PerformanceWeights,
}

impl InitializeConfigInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `InitializeConfig`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` payer
///   1. `[optional]` program (default to `86oGodFG8DfLYHAgYwUPCNQzaods7Auxz9cnU7XzWipt`)
///   2. `[]` program_data
///   3. `[writable]` config
///   4. `[writable, signer]` reward_mint
///   5. `[]` mint_authority
///   6. `[writable]` sol_reserve
///   7. `[writable]` token_reserve_vault
///   8. `[optional]` system_program (default to `11111111111111111111111111111111`)
///   9. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
#[derive(Clone, Debug, Default)]
pub struct InitializeConfigBuilder {
    payer: Option<solana_address::Address>,
    program: Option<solana_address::Address>,
    program_data: Option<solana_address::Address>,
    config: Option<solana_address::Address>,
    reward_mint: Option<solana_address::Address>,
    mint_authority: Option<solana_address::Address>,
    sol_reserve: Option<solana_address::Address>,
    token_reserve_vault: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    token_program: Option<solana_address::Address>,
    admin: Option<Address>,
    oracle: Option<Address>,
    claim_window_slots: Option<u64>,
    curve: Option<CurveParams>,
    performance_weights: Option<PerformanceWeights>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl InitializeConfigBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn payer(&mut self, payer: solana_address::Address) -> &mut Self {
        self.payer = Some(payer);
        self
    }
    /// `[optional account, default to '86oGodFG8DfLYHAgYwUPCNQzaods7Auxz9cnU7XzWipt']`
    #[inline(always)]
    pub fn program(&mut self, program: solana_address::Address) -> &mut Self {
        self.program = Some(program);
        self
    }
    #[inline(always)]
    pub fn program_data(&mut self, program_data: solana_address::Address) -> &mut Self {
        self.program_data = Some(program_data);
        self
    }
    #[inline(always)]
    pub fn config(&mut self, config: solana_address::Address) -> &mut Self {
        self.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn reward_mint(&mut self, reward_mint: solana_address::Address) -> &mut Self {
        self.reward_mint = Some(reward_mint);
        self
    }
    #[inline(always)]
    pub fn mint_authority(&mut self, mint_authority: solana_address::Address) -> &mut Self {
        self.mint_authority = Some(mint_authority);
        self
    }
    #[inline(always)]
    pub fn sol_reserve(&mut self, sol_reserve: solana_address::Address) -> &mut Self {
        self.sol_reserve = Some(sol_reserve);
        self
    }
    #[inline(always)]
    pub fn token_reserve_vault(
        &mut self,
        token_reserve_vault: solana_address::Address,
    ) -> &mut Self {
        self.token_reserve_vault = Some(token_reserve_vault);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_address::Address) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn admin(&mut self, admin: Address) -> &mut Self {
        self.admin = Some(admin);
        self
    }
    #[inline(always)]
    pub fn oracle(&mut self, oracle: Address) -> &mut Self {
        self.oracle = Some(oracle);
        self
    }
    #[inline(always)]
    pub fn claim_window_slots(&mut self, claim_window_slots: u64) -> &mut Self {
        self.claim_window_slots = Some(claim_window_slots);
        self
    }
    #[inline(always)]
    pub fn curve(&mut self, curve: CurveParams) -> &mut Self {
        self.curve = Some(curve);
        self
    }
    #[inline(always)]
    pub fn performance_weights(&mut self, performance_weights: PerformanceWeights) -> &mut Self {
        self.performance_weights = Some(performance_weights);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = InitializeConfig {
            payer: self.payer.expect("payer is not set"),
            program: self.program.unwrap_or(solana_address::address!(
                "86oGodFG8DfLYHAgYwUPCNQzaods7Auxz9cnU7XzWipt"
            )),
            program_data: self.program_data.expect("program_data is not set"),
            config: self.config.expect("config is not set"),
            reward_mint: self.reward_mint.expect("reward_mint is not set"),
            mint_authority: self.mint_authority.expect("mint_authority is not set"),
            sol_reserve: self.sol_reserve.expect("sol_reserve is not set"),
            token_reserve_vault: self
                .token_reserve_vault
                .expect("token_reserve_vault is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
            token_program: self.token_program.unwrap_or(solana_address::address!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
        };
        let args = InitializeConfigInstructionArgs {
            admin: self.admin.clone().expect("admin is not set"),
            oracle: self.oracle.clone().expect("oracle is not set"),
            claim_window_slots: self
                .claim_window_slots
                .clone()
                .expect("claim_window_slots is not set"),
            curve: self.curve.clone().expect("curve is not set"),
            performance_weights: self
                .performance_weights
                .clone()
                .expect("performance_weights is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `initialize_config` CPI accounts.
pub struct InitializeConfigCpiAccounts<'a, 'b> {
    pub payer: &'b solana_account_info::AccountInfo<'a>,

    pub program: &'b solana_account_info::AccountInfo<'a>,

    pub program_data: &'b solana_account_info::AccountInfo<'a>,

    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub reward_mint: &'b solana_account_info::AccountInfo<'a>,

    pub mint_authority: &'b solana_account_info::AccountInfo<'a>,

    pub sol_reserve: &'b solana_account_info::AccountInfo<'a>,

    pub token_reserve_vault: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `initialize_config` CPI instruction.
pub struct InitializeConfigCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub payer: &'b solana_account_info::AccountInfo<'a>,

    pub program: &'b solana_account_info::AccountInfo<'a>,

    pub program_data: &'b solana_account_info::AccountInfo<'a>,

    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub reward_mint: &'b solana_account_info::AccountInfo<'a>,

    pub mint_authority: &'b solana_account_info::AccountInfo<'a>,

    pub sol_reserve: &'b solana_account_info::AccountInfo<'a>,

    pub token_reserve_vault: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: InitializeConfigInstructionArgs,
}

impl<'a, 'b> InitializeConfigCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: InitializeConfigCpiAccounts<'a, 'b>,
        args: InitializeConfigInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            payer: accounts.payer,
            program: accounts.program,
            program_data: accounts.program_data,
            config: accounts.config,
            reward_mint: accounts.reward_mint,
            mint_authority: accounts.mint_authority,
            sol_reserve: accounts.sol_reserve,
            token_reserve_vault: accounts.token_reserve_vault,
            system_program: accounts.system_program,
            token_program: accounts.token_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(10 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.payer.key, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.program_data.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.reward_mint.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.mint_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.sol_reserve.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_reserve_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = InitializeConfigInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::PCN_PROGRAM_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(11 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.payer.clone());
        account_infos.push(self.program.clone());
        account_infos.push(self.program_data.clone());
        account_infos.push(self.config.clone());
        account_infos.push(self.reward_mint.clone());
        account_infos.push(self.mint_authority.clone());
        account_infos.push(self.sol_reserve.clone());
        account_infos.push(self.token_reserve_vault.clone());
        account_infos.push(self.system_program.clone());
        account_infos.push(self.token_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `InitializeConfig` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` payer
///   1. `[]` program
///   2. `[]` program_data
///   3. `[writable]` config
///   4. `[writable, signer]` reward_mint
///   5. `[]` mint_authority
///   6. `[writable]` sol_reserve
///   7. `[writable]` token_reserve_vault
///   8. `[]` system_program
///   9. `[]` token_program
#[derive(Clone, Debug)]
pub struct InitializeConfigCpiBuilder<'a, 'b> {
    instruction: Box<InitializeConfigCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> InitializeConfigCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(InitializeConfigCpiBuilderInstruction {
            __program: program,
            payer: None,
            program: None,
            program_data: None,
            config: None,
            reward_mint: None,
            mint_authority: None,
            sol_reserve: None,
            token_reserve_vault: None,
            system_program: None,
            token_program: None,
            admin: None,
            oracle: None,
            claim_window_slots: None,
            curve: None,
            performance_weights: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.payer = Some(payer);
        self
    }
    #[inline(always)]
    pub fn program(&mut self, program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.program = Some(program);
        self
    }
    #[inline(always)]
    pub fn program_data(
        &mut self,
        program_data: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.program_data = Some(program_data);
        self
    }
    #[inline(always)]
    pub fn config(&mut self, config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn reward_mint(
        &mut self,
        reward_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.reward_mint = Some(reward_mint);
        self
    }
    #[inline(always)]
    pub fn mint_authority(
        &mut self,
        mint_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.mint_authority = Some(mint_authority);
        self
    }
    #[inline(always)]
    pub fn sol_reserve(
        &mut self,
        sol_reserve: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.sol_reserve = Some(sol_reserve);
        self
    }
    #[inline(always)]
    pub fn token_reserve_vault(
        &mut self,
        token_reserve_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_reserve_vault = Some(token_reserve_vault);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn admin(&mut self, admin: Address) -> &mut Self {
        self.instruction.admin = Some(admin);
        self
    }
    #[inline(always)]
    pub fn oracle(&mut self, oracle: Address) -> &mut Self {
        self.instruction.oracle = Some(oracle);
        self
    }
    #[inline(always)]
    pub fn claim_window_slots(&mut self, claim_window_slots: u64) -> &mut Self {
        self.instruction.claim_window_slots = Some(claim_window_slots);
        self
    }
    #[inline(always)]
    pub fn curve(&mut self, curve: CurveParams) -> &mut Self {
        self.instruction.curve = Some(curve);
        self
    }
    #[inline(always)]
    pub fn performance_weights(&mut self, performance_weights: PerformanceWeights) -> &mut Self {
        self.instruction.performance_weights = Some(performance_weights);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = InitializeConfigInstructionArgs {
            admin: self.instruction.admin.clone().expect("admin is not set"),
            oracle: self.instruction.oracle.clone().expect("oracle is not set"),
            claim_window_slots: self
                .instruction
                .claim_window_slots
                .clone()
                .expect("claim_window_slots is not set"),
            curve: self.instruction.curve.clone().expect("curve is not set"),
            performance_weights: self
                .instruction
                .performance_weights
                .clone()
                .expect("performance_weights is not set"),
        };
        let instruction = InitializeConfigCpi {
            __program: self.instruction.__program,

            payer: self.instruction.payer.expect("payer is not set"),

            program: self.instruction.program.expect("program is not set"),

            program_data: self
                .instruction
                .program_data
                .expect("program_data is not set"),

            config: self.instruction.config.expect("config is not set"),

            reward_mint: self
                .instruction
                .reward_mint
                .expect("reward_mint is not set"),

            mint_authority: self
                .instruction
                .mint_authority
                .expect("mint_authority is not set"),

            sol_reserve: self
                .instruction
                .sol_reserve
                .expect("sol_reserve is not set"),

            token_reserve_vault: self
                .instruction
                .token_reserve_vault
                .expect("token_reserve_vault is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct InitializeConfigCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    payer: Option<&'b solana_account_info::AccountInfo<'a>>,
    program: Option<&'b solana_account_info::AccountInfo<'a>>,
    program_data: Option<&'b solana_account_info::AccountInfo<'a>>,
    config: Option<&'b solana_account_info::AccountInfo<'a>>,
    reward_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    mint_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    sol_reserve: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_reserve_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    admin: Option<Address>,
    oracle: Option<Address>,
    claim_window_slots: Option<u64>,
    curve: Option<CurveParams>,
    performance_weights: Option<PerformanceWeights>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
