//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const OPEN_EPOCH_DISCRIMINATOR: [u8; 8] = [75, 57, 218, 33, 173, 254, 207, 136];

/// Accounts.
#[derive(Debug)]
pub struct OpenEpoch {
    pub oracle: solana_address::Address,

    pub funder: solana_address::Address,

    pub config: solana_address::Address,

    pub epoch: solana_address::Address,

    pub epoch_token_vault: solana_address::Address,

    pub mint_authority: solana_address::Address,

    pub reward_mint: solana_address::Address,

    pub system_program: solana_address::Address,

    pub token_program: solana_address::Address,

    pub rent: solana_address::Address,
}

impl OpenEpoch {
    pub fn instruction(&self, args: OpenEpochInstructionArgs) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: OpenEpochInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(10 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.oracle,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.funder, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.epoch, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.epoch_token_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.mint_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.reward_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.rent, false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = OpenEpochInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::PCN_PROGRAM_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct OpenEpochInstructionData {
    discriminator: [u8; 8],
}

impl OpenEpochInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [75, 57, 218, 33, 173, 254, 207, 136],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for OpenEpochInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct OpenEpochInstructionArgs {
    pub epoch_id: u64,
    pub start_slot: u64,
    pub end_slot: u64,
    pub support_budget_lamports: u64,
}

impl OpenEpochInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `OpenEpoch`.
///
/// ### Accounts:
///
///   0. `[signer]` oracle
///   1. `[writable, signer]` funder
///   2. `[]` config
///   3. `[writable]` epoch
///   4. `[writable]` epoch_token_vault
///   5. `[]` mint_authority
///   6. `[]` reward_mint
///   7. `[optional]` system_program (default to `11111111111111111111111111111111`)
///   8. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
///   9. `[optional]` rent (default to `SysvarRent111111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct OpenEpochBuilder {
    oracle: Option<solana_address::Address>,
    funder: Option<solana_address::Address>,
    config: Option<solana_address::Address>,
    epoch: Option<solana_address::Address>,
    epoch_token_vault: Option<solana_address::Address>,
    mint_authority: Option<solana_address::Address>,
    reward_mint: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    token_program: Option<solana_address::Address>,
    rent: Option<solana_address::Address>,
    epoch_id: Option<u64>,
    start_slot: Option<u64>,
    end_slot: Option<u64>,
    support_budget_lamports: Option<u64>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl OpenEpochBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn oracle(&mut self, oracle: solana_address::Address) -> &mut Self {
        self.oracle = Some(oracle);
        self
    }
    #[inline(always)]
    pub fn funder(&mut self, funder: solana_address::Address) -> &mut Self {
        self.funder = Some(funder);
        self
    }
    #[inline(always)]
    pub fn config(&mut self, config: solana_address::Address) -> &mut Self {
        self.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn epoch(&mut self, epoch: solana_address::Address) -> &mut Self {
        self.epoch = Some(epoch);
        self
    }
    #[inline(always)]
    pub fn epoch_token_vault(&mut self, epoch_token_vault: solana_address::Address) -> &mut Self {
        self.epoch_token_vault = Some(epoch_token_vault);
        self
    }
    #[inline(always)]
    pub fn mint_authority(&mut self, mint_authority: solana_address::Address) -> &mut Self {
        self.mint_authority = Some(mint_authority);
        self
    }
    #[inline(always)]
    pub fn reward_mint(&mut self, reward_mint: solana_address::Address) -> &mut Self {
        self.reward_mint = Some(reward_mint);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_address::Address) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }
    /// `[optional account, default to 'SysvarRent111111111111111111111111111111111']`
    #[inline(always)]
    pub fn rent(&mut self, rent: solana_address::Address) -> &mut Self {
        self.rent = Some(rent);
        self
    }
    #[inline(always)]
    pub fn epoch_id(&mut self, epoch_id: u64) -> &mut Self {
        self.epoch_id = Some(epoch_id);
        self
    }
    #[inline(always)]
    pub fn start_slot(&mut self, start_slot: u64) -> &mut Self {
        self.start_slot = Some(start_slot);
        self
    }
    #[inline(always)]
    pub fn end_slot(&mut self, end_slot: u64) -> &mut Self {
        self.end_slot = Some(end_slot);
        self
    }
    #[inline(always)]
    pub fn support_budget_lamports(&mut self, support_budget_lamports: u64) -> &mut Self {
        self.support_budget_lamports = Some(support_budget_lamports);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = OpenEpoch {
            oracle: self.oracle.expect("oracle is not set"),
            funder: self.funder.expect("funder is not set"),
            config: self.config.expect("config is not set"),
            epoch: self.epoch.expect("epoch is not set"),
            epoch_token_vault: self
                .epoch_token_vault
                .expect("epoch_token_vault is not set"),
            mint_authority: self.mint_authority.expect("mint_authority is not set"),
            reward_mint: self.reward_mint.expect("reward_mint is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
            token_program: self.token_program.unwrap_or(solana_address::address!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
            rent: self.rent.unwrap_or(solana_address::address!(
                "SysvarRent111111111111111111111111111111111"
            )),
        };
        let args = OpenEpochInstructionArgs {
            epoch_id: self.epoch_id.clone().expect("epoch_id is not set"),
            start_slot: self.start_slot.clone().expect("start_slot is not set"),
            end_slot: self.end_slot.clone().expect("end_slot is not set"),
            support_budget_lamports: self
                .support_budget_lamports
                .clone()
                .expect("support_budget_lamports is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `open_epoch` CPI accounts.
pub struct OpenEpochCpiAccounts<'a, 'b> {
    pub oracle: &'b solana_account_info::AccountInfo<'a>,

    pub funder: &'b solana_account_info::AccountInfo<'a>,

    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub epoch: &'b solana_account_info::AccountInfo<'a>,

    pub epoch_token_vault: &'b solana_account_info::AccountInfo<'a>,

    pub mint_authority: &'b solana_account_info::AccountInfo<'a>,

    pub reward_mint: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,

    pub rent: &'b solana_account_info::AccountInfo<'a>,
}

/// `open_epoch` CPI instruction.
pub struct OpenEpochCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub oracle: &'b solana_account_info::AccountInfo<'a>,

    pub funder: &'b solana_account_info::AccountInfo<'a>,

    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub epoch: &'b solana_account_info::AccountInfo<'a>,

    pub epoch_token_vault: &'b solana_account_info::AccountInfo<'a>,

    pub mint_authority: &'b solana_account_info::AccountInfo<'a>,

    pub reward_mint: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,

    pub rent: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: OpenEpochInstructionArgs,
}

impl<'a, 'b> OpenEpochCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: OpenEpochCpiAccounts<'a, 'b>,
        args: OpenEpochInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            oracle: accounts.oracle,
            funder: accounts.funder,
            config: accounts.config,
            epoch: accounts.epoch,
            epoch_token_vault: accounts.epoch_token_vault,
            mint_authority: accounts.mint_authority,
            reward_mint: accounts.reward_mint,
            system_program: accounts.system_program,
            token_program: accounts.token_program,
            rent: accounts.rent,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(10 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.oracle.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.funder.key, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.epoch.key, false));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.epoch_token_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.mint_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.reward_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.rent.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = OpenEpochInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::PCN_PROGRAM_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(11 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.oracle.clone());
        account_infos.push(self.funder.clone());
        account_infos.push(self.config.clone());
        account_infos.push(self.epoch.clone());
        account_infos.push(self.epoch_token_vault.clone());
        account_infos.push(self.mint_authority.clone());
        account_infos.push(self.reward_mint.clone());
        account_infos.push(self.system_program.clone());
        account_infos.push(self.token_program.clone());
        account_infos.push(self.rent.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `OpenEpoch` via CPI.
///
/// ### Accounts:
///
///   0. `[signer]` oracle
///   1. `[writable, signer]` funder
///   2. `[]` config
///   3. `[writable]` epoch
///   4. `[writable]` epoch_token_vault
///   5. `[]` mint_authority
///   6. `[]` reward_mint
///   7. `[]` system_program
///   8. `[]` token_program
///   9. `[]` rent
#[derive(Clone, Debug)]
pub struct OpenEpochCpiBuilder<'a, 'b> {
    instruction: Box<OpenEpochCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> OpenEpochCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(OpenEpochCpiBuilderInstruction {
            __program: program,
            oracle: None,
            funder: None,
            config: None,
            epoch: None,
            epoch_token_vault: None,
            mint_authority: None,
            reward_mint: None,
            system_program: None,
            token_program: None,
            rent: None,
            epoch_id: None,
            start_slot: None,
            end_slot: None,
            support_budget_lamports: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn oracle(&mut self, oracle: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.oracle = Some(oracle);
        self
    }
    #[inline(always)]
    pub fn funder(&mut self, funder: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.funder = Some(funder);
        self
    }
    #[inline(always)]
    pub fn config(&mut self, config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn epoch(&mut self, epoch: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.epoch = Some(epoch);
        self
    }
    #[inline(always)]
    pub fn epoch_token_vault(
        &mut self,
        epoch_token_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.epoch_token_vault = Some(epoch_token_vault);
        self
    }
    #[inline(always)]
    pub fn mint_authority(
        &mut self,
        mint_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.mint_authority = Some(mint_authority);
        self
    }
    #[inline(always)]
    pub fn reward_mint(
        &mut self,
        reward_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.reward_mint = Some(reward_mint);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn rent(&mut self, rent: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.rent = Some(rent);
        self
    }
    #[inline(always)]
    pub fn epoch_id(&mut self, epoch_id: u64) -> &mut Self {
        self.instruction.epoch_id = Some(epoch_id);
        self
    }
    #[inline(always)]
    pub fn start_slot(&mut self, start_slot: u64) -> &mut Self {
        self.instruction.start_slot = Some(start_slot);
        self
    }
    #[inline(always)]
    pub fn end_slot(&mut self, end_slot: u64) -> &mut Self {
        self.instruction.end_slot = Some(end_slot);
        self
    }
    #[inline(always)]
    pub fn support_budget_lamports(&mut self, support_budget_lamports: u64) -> &mut Self {
        self.instruction.support_budget_lamports = Some(support_budget_lamports);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = OpenEpochInstructionArgs {
            epoch_id: self
                .instruction
                .epoch_id
                .clone()
                .expect("epoch_id is not set"),
            start_slot: self
                .instruction
                .start_slot
                .clone()
                .expect("start_slot is not set"),
            end_slot: self
                .instruction
                .end_slot
                .clone()
                .expect("end_slot is not set"),
            support_budget_lamports: self
                .instruction
                .support_budget_lamports
                .clone()
                .expect("support_budget_lamports is not set"),
        };
        let instruction = OpenEpochCpi {
            __program: self.instruction.__program,

            oracle: self.instruction.oracle.expect("oracle is not set"),

            funder: self.instruction.funder.expect("funder is not set"),

            config: self.instruction.config.expect("config is not set"),

            epoch: self.instruction.epoch.expect("epoch is not set"),

            epoch_token_vault: self
                .instruction
                .epoch_token_vault
                .expect("epoch_token_vault is not set"),

            mint_authority: self
                .instruction
                .mint_authority
                .expect("mint_authority is not set"),

            reward_mint: self
                .instruction
                .reward_mint
                .expect("reward_mint is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),

            rent: self.instruction.rent.expect("rent is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct OpenEpochCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    oracle: Option<&'b solana_account_info::AccountInfo<'a>>,
    funder: Option<&'b solana_account_info::AccountInfo<'a>>,
    config: Option<&'b solana_account_info::AccountInfo<'a>>,
    epoch: Option<&'b solana_account_info::AccountInfo<'a>>,
    epoch_token_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    mint_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    reward_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    rent: Option<&'b solana_account_info::AccountInfo<'a>>,
    epoch_id: Option<u64>,
    start_slot: Option<u64>,
    end_slot: Option<u64>,
    support_budget_lamports: Option<u64>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
