/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  extendClient,
  fixEncoderSize,
  getBytesEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
  SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
  SolanaError,
  type Address,
  type ClientWithPayer,
  type ClientWithRpc,
  type ClientWithTransactionPlanning,
  type ClientWithTransactionSending,
  type ExtendedClient,
  type GetAccountInfoApi,
  type GetMultipleAccountsApi,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  addSelfFetchFunctions,
  addSelfPlanAndSendFunctions,
  type SelfFetchFunctions,
  type SelfPlanAndSendFunctions,
} from "@solana/program-client-core";
import {
  getClaimCodec,
  getConfigCodec,
  getEpochCodec,
  getSolReserveCodec,
  type Claim,
  type ClaimArgs,
  type Config,
  type ConfigArgs,
  type Epoch,
  type EpochArgs,
  type SolReserve,
  type SolReserveArgs,
} from "../accounts";
import {
  getClaimRewardInstructionAsync,
  getCreateClaimInstructionAsync,
  getFinalizeEpochInstructionAsync,
  getInitializeConfigInstructionAsync,
  getOpenEpochInstructionAsync,
  getSweepEpochInstructionAsync,
  getUpdateConfigInstructionAsync,
  parseClaimRewardInstruction,
  parseCreateClaimInstruction,
  parseFinalizeEpochInstruction,
  parseInitializeConfigInstruction,
  parseOpenEpochInstruction,
  parseSweepEpochInstruction,
  parseUpdateConfigInstruction,
  type ClaimRewardAsyncInput,
  type CreateClaimAsyncInput,
  type FinalizeEpochAsyncInput,
  type InitializeConfigAsyncInput,
  type OpenEpochAsyncInput,
  type ParsedClaimRewardInstruction,
  type ParsedCreateClaimInstruction,
  type ParsedFinalizeEpochInstruction,
  type ParsedInitializeConfigInstruction,
  type ParsedOpenEpochInstruction,
  type ParsedSweepEpochInstruction,
  type ParsedUpdateConfigInstruction,
  type SweepEpochAsyncInput,
  type UpdateConfigAsyncInput,
} from "../instructions";
import {
  findConfigPda,
  findMintAuthorityPda,
  findSolReservePda,
  findTokenReserveVaultPda,
} from "../pdas";

export const PCN_PROGRAM_PROGRAM_ADDRESS =
  "86oGodFG8DfLYHAgYwUPCNQzaods7Auxz9cnU7XzWipt" as Address<"86oGodFG8DfLYHAgYwUPCNQzaods7Auxz9cnU7XzWipt">;

export enum PcnProgramAccount {
  Claim,
  Config,
  Epoch,
  SolReserve,
}

export function identifyPcnProgramAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): PcnProgramAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([155, 70, 22, 176, 123, 215, 246, 102])
      ),
      0
    )
  ) {
    return PcnProgramAccount.Claim;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([155, 12, 170, 224, 30, 250, 204, 130])
      ),
      0
    )
  ) {
    return PcnProgramAccount.Config;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([93, 83, 120, 89, 151, 138, 152, 108])
      ),
      0
    )
  ) {
    return PcnProgramAccount.Epoch;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([78, 170, 214, 85, 103, 74, 70, 180])
      ),
      0
    )
  ) {
    return PcnProgramAccount.SolReserve;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
    { accountData: data, programName: "pcnProgram" }
  );
}

export enum PcnProgramInstruction {
  ClaimReward,
  CreateClaim,
  FinalizeEpoch,
  InitializeConfig,
  OpenEpoch,
  SweepEpoch,
  UpdateConfig,
}

export function identifyPcnProgramInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): PcnProgramInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([149, 95, 181, 242, 94, 90, 158, 162])
      ),
      0
    )
  ) {
    return PcnProgramInstruction.ClaimReward;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([71, 122, 43, 84, 240, 165, 215, 181])
      ),
      0
    )
  ) {
    return PcnProgramInstruction.CreateClaim;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([159, 93, 117, 217, 63, 44, 249, 76])
      ),
      0
    )
  ) {
    return PcnProgramInstruction.FinalizeEpoch;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([208, 127, 21, 1, 194, 190, 196, 70])
      ),
      0
    )
  ) {
    return PcnProgramInstruction.InitializeConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([75, 57, 218, 33, 173, 254, 207, 136])
      ),
      0
    )
  ) {
    return PcnProgramInstruction.OpenEpoch;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([187, 9, 52, 111, 60, 24, 52, 28])
      ),
      0
    )
  ) {
    return PcnProgramInstruction.SweepEpoch;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([29, 158, 252, 191, 10, 83, 219, 99])
      ),
      0
    )
  ) {
    return PcnProgramInstruction.UpdateConfig;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
    { instructionData: data, programName: "pcnProgram" }
  );
}

export type ParsedPcnProgramInstruction<
  TProgram extends string = "86oGodFG8DfLYHAgYwUPCNQzaods7Auxz9cnU7XzWipt"
> =
  | ({
      instructionType: PcnProgramInstruction.ClaimReward;
    } & ParsedClaimRewardInstruction<TProgram>)
  | ({
      instructionType: PcnProgramInstruction.CreateClaim;
    } & ParsedCreateClaimInstruction<TProgram>)
  | ({
      instructionType: PcnProgramInstruction.FinalizeEpoch;
    } & ParsedFinalizeEpochInstruction<TProgram>)
  | ({
      instructionType: PcnProgramInstruction.InitializeConfig;
    } & ParsedInitializeConfigInstruction<TProgram>)
  | ({
      instructionType: PcnProgramInstruction.OpenEpoch;
    } & ParsedOpenEpochInstruction<TProgram>)
  | ({
      instructionType: PcnProgramInstruction.SweepEpoch;
    } & ParsedSweepEpochInstruction<TProgram>)
  | ({
      instructionType: PcnProgramInstruction.UpdateConfig;
    } & ParsedUpdateConfigInstruction<TProgram>);

export function parsePcnProgramInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>
): ParsedPcnProgramInstruction<TProgram> {
  const instructionType = identifyPcnProgramInstruction(instruction);
  switch (instructionType) {
    case PcnProgramInstruction.ClaimReward: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: PcnProgramInstruction.ClaimReward,
        ...parseClaimRewardInstruction(instruction),
      };
    }
    case PcnProgramInstruction.CreateClaim: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: PcnProgramInstruction.CreateClaim,
        ...parseCreateClaimInstruction(instruction),
      };
    }
    case PcnProgramInstruction.FinalizeEpoch: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: PcnProgramInstruction.FinalizeEpoch,
        ...parseFinalizeEpochInstruction(instruction),
      };
    }
    case PcnProgramInstruction.InitializeConfig: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: PcnProgramInstruction.InitializeConfig,
        ...parseInitializeConfigInstruction(instruction),
      };
    }
    case PcnProgramInstruction.OpenEpoch: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: PcnProgramInstruction.OpenEpoch,
        ...parseOpenEpochInstruction(instruction),
      };
    }
    case PcnProgramInstruction.SweepEpoch: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: PcnProgramInstruction.SweepEpoch,
        ...parseSweepEpochInstruction(instruction),
      };
    }
    case PcnProgramInstruction.UpdateConfig: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: PcnProgramInstruction.UpdateConfig,
        ...parseUpdateConfigInstruction(instruction),
      };
    }
    default:
      throw new SolanaError(
        SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
        {
          instructionType: instructionType as string,
          programName: "pcnProgram",
        }
      );
  }
}

export type PcnProgramPlugin = {
  accounts: PcnProgramPluginAccounts;
  instructions: PcnProgramPluginInstructions;
  pdas: PcnProgramPluginPdas;
  identifyAccount: typeof identifyPcnProgramAccount;
  identifyInstruction: typeof identifyPcnProgramInstruction;
  parseInstruction: typeof parsePcnProgramInstruction;
};

export type PcnProgramPluginAccounts = {
  claim: ReturnType<typeof getClaimCodec> &
    SelfFetchFunctions<ClaimArgs, Claim>;
  config: ReturnType<typeof getConfigCodec> &
    SelfFetchFunctions<ConfigArgs, Config>;
  epoch: ReturnType<typeof getEpochCodec> &
    SelfFetchFunctions<EpochArgs, Epoch>;
  solReserve: ReturnType<typeof getSolReserveCodec> &
    SelfFetchFunctions<SolReserveArgs, SolReserve>;
};

export type PcnProgramPluginInstructions = {
  claimReward: (
    input: ClaimRewardAsyncInput
  ) => ReturnType<typeof getClaimRewardInstructionAsync> &
    SelfPlanAndSendFunctions;
  createClaim: (
    input: MakeOptional<CreateClaimAsyncInput, "payer">
  ) => ReturnType<typeof getCreateClaimInstructionAsync> &
    SelfPlanAndSendFunctions;
  finalizeEpoch: (
    input: FinalizeEpochAsyncInput
  ) => ReturnType<typeof getFinalizeEpochInstructionAsync> &
    SelfPlanAndSendFunctions;
  initializeConfig: (
    input: MakeOptional<InitializeConfigAsyncInput, "payer">
  ) => ReturnType<typeof getInitializeConfigInstructionAsync> &
    SelfPlanAndSendFunctions;
  openEpoch: (
    input: OpenEpochAsyncInput
  ) => ReturnType<typeof getOpenEpochInstructionAsync> &
    SelfPlanAndSendFunctions;
  sweepEpoch: (
    input: SweepEpochAsyncInput
  ) => ReturnType<typeof getSweepEpochInstructionAsync> &
    SelfPlanAndSendFunctions;
  updateConfig: (
    input: UpdateConfigAsyncInput
  ) => ReturnType<typeof getUpdateConfigInstructionAsync> &
    SelfPlanAndSendFunctions;
};

export type PcnProgramPluginPdas = {
  config: typeof findConfigPda;
  mintAuthority: typeof findMintAuthorityPda;
  solReserve: typeof findSolReservePda;
  tokenReserveVault: typeof findTokenReserveVaultPda;
};

export type PcnProgramPluginRequirements = ClientWithRpc<
  GetAccountInfoApi & GetMultipleAccountsApi
> &
  ClientWithPayer &
  ClientWithTransactionPlanning &
  ClientWithTransactionSending;

export function pcnProgramProgram() {
  return <T extends PcnProgramPluginRequirements>(
    client: T
  ): ExtendedClient<T, { pcnProgram: PcnProgramPlugin }> => {
    return extendClient(client, {
      pcnProgram: <PcnProgramPlugin>{
        accounts: {
          claim: addSelfFetchFunctions(client, getClaimCodec()),
          config: addSelfFetchFunctions(client, getConfigCodec()),
          epoch: addSelfFetchFunctions(client, getEpochCodec()),
          solReserve: addSelfFetchFunctions(client, getSolReserveCodec()),
        },
        instructions: {
          claimReward: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getClaimRewardInstructionAsync(input)
            ),
          createClaim: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getCreateClaimInstructionAsync({
                ...input,
                payer: input.payer ?? client.payer,
              })
            ),
          finalizeEpoch: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getFinalizeEpochInstructionAsync(input)
            ),
          initializeConfig: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitializeConfigInstructionAsync({
                ...input,
                payer: input.payer ?? client.payer,
              })
            ),
          openEpoch: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getOpenEpochInstructionAsync(input)
            ),
          sweepEpoch: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getSweepEpochInstructionAsync(input)
            ),
          updateConfig: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getUpdateConfigInstructionAsync(input)
            ),
        },
        pdas: {
          config: findConfigPda,
          mintAuthority: findMintAuthorityPda,
          solReserve: findSolReservePda,
          tokenReserveVault: findTokenReserveVaultPda,
        },
        identifyAccount: identifyPcnProgramAccount,
        identifyInstruction: identifyPcnProgramInstruction,
        parseInstruction: parsePcnProgramInstruction,
      },
    });
  };
}

type MakeOptional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;
